import type { EdidVendorIdMap } from './edid-vendor-types';

export const EDID_VENDOR_ID_MAP: EdidVendorIdMap = {
  AAA: `Avolites`,
  AAE: `Anatek Electronics`,
  AAM: `Aava Mobile Oy`,
  AAN: `AAEON Technology`,
  AAT: `Ann Arbor Technologies`,
  ABA: `ABBAHOME`,
  ABC: `AboCom System`,
  ABD: `Allen Bradley Company`,
  ABE: `Alcatel Bell`,
  ABO: `D-Link Systems`,
  ABS: `Abaco Systems`,
  ABT: `Anchor Bay Technologies`,
  ABV: `Advanced Research Technology`,
  ACA: `Ariel Corporation`,
  ACB: `Aculab`,
  ACC: `Accton Technology Corporation`,
  ACD: `AWETA BV`,
  ACE: `Actek Engineering`,
  ACG: `A&R Cambridge`,
  ACH: `Archtek Telecom Corporation`,
  ACI: `AsusTek Computer`,
  ACK: `Acksys`,
  ACL: `Apricot Computers`,
  ACM: `Acroloop Motion Control Systems`,
  ACO: `Allion Computer`,
  ACP: `Aspen Tech`,
  ACR: `Acer Technologies`,
  ACS: `Altos Computer Systems`,
  ACT: `Targa`,
  ACU: `Acculogic`,
  ACV: `ActivCard S.A`,
  ADA: `Addi-Data GmbH`,
  ADB: `Aldebbaron`,
  ADC: `Acnhor Datacomm`,
  ADD: `Advanced Peripheral Devices`,
  ADE: `Arithmos`,
  ADG: `Airdrop Gaming`,
  ADH: `Aerodata Holdings`,
  ADI: `ADI Systems`,
  ADK: `Adtek System Science Company`,
  ADL: `ASTRA Security Products`,
  ADM: `Ad Lib MultiMedia`,
  ADN: `Analog & Digital Devices Tel.`,
  ADP: `Adaptec`,
  ADR: `Nasa Ames Research Center`,
  ADS: `Analog Devices`,
  ADT: `Adtek`,
  ADV: `Advanced Micro Devices`,
  ADX: `Adax`,
  ADZ: `Adder Technology`,
  AEC: `Antex Electronics Corporation`,
  AED: `Advanced Electronic Designs`,
  AEI: `Actiontec Electric`,
  AEJ: `Alpha Electronics Company`,
  AEM: `ASEM S.p.A.`,
  AEN: `Avencall`,
  AEP: `Aetas Peripheral International`,
  AET: `Aethra Telecomunicazioni S.r.l.`,
  AFA: `Alfa`,
  AGC: `Beijing Aerospace Golden Card Electronic Engineering`,
  AGI: `Artish Graphics`,
  AGL: `Argolis`,
  AGM: `Advan Int'l Corporation`,
  AGO: `AlgolTek`,
  AGT: `Agilent Technologies`,
  AHC: `Advantech`,
  AHQ: `Astro HQ`,
  AHS: `Beijing AnHeng SecoTech Information Technology`,
  AIC: `Arnos Insturments & Computer Systems`,
  AIE: `Altmann Industrieelektronik`,
  AII: `Amptron International`,
  AIK: `Dongguan Alllike Electronics`,
  AIL: `Altos India`,
  AIM: `AIMS Lab`,
  AIR: `Advanced Integ. Research`,
  AIS: `Alien Internet Services`,
  AIW: `Aiwa Company`,
  AIX: `Altinex`,
  AJA: `AJA Video Systems`,
  AKB: `Akebia`,
  AKE: `AKAMI Electric`,
  AKI: `AKIA Corporation`,
  AKL: `AMiT`,
  AKM: `Asahi Kasei Microsystems Company`,
  AKP: `Atom Komplex Prylad`,
  AKR: `Anker Innovations`,
  AKY: `Askey Computer Corporation`,
  ALA: `Alacron`,
  ALC: `Altec Corporation`,
  ALD: `In4S`,
  ALE: `Alenco BV`,
  ALG: `Realtek Semiconductor Corp.`,
  ALH: `AL Systems`,
  ALI: `Acer Labs`,
  ALJ: `Altec Lansing`,
  ALK: `Acrolink`,
  ALL: `Alliance Semiconductor Corporation`,
  ALM: `Acutec`,
  ALN: `Alana Technologies`,
  ALO: `Algolith`,
  ALP: `Alps Alpine`,
  ALR: `Advanced Logic`,
  ALS: `Avance Logic`,
  ALT: `Altra`,
  ALV: `AlphaView LCD`,
  ALX: `Alexon`,
  AMA: `Asia Microelectronic Development`,
  AMB: `Ambient Technologies`,
  AMC: `Attachmate Corporation`,
  AMD: `Amdek Corporation`,
  AMI: `American Megatrends`,
  AML: `Anderson Multimedia Communications (HK)`,
  AMN: `Amimon`,
  AMO: `Amino Technologies PLC and Amino Communications`,
  AMP: `AMP`,
  AMR: `AmTRAN Technology`,
  AMS: `ARMSTEL`,
  AMT: `AMT International Industry`,
  AMX: `AMX`,
  ANA: `Anakron`,
  ANC: `Ancot`,
  AND: `Adtran`,
  ANI: `Anigma`,
  ANK: `Anko Electronic Company`,
  ANL: `Analogix Semiconductor`,
  ANO: `Anorad Corporation`,
  ANP: `Andrew Network Production`,
  ANR: `ANR`,
  ANS: `Ansel Communication Company`,
  ANT: `Ace CAD Enterprise Company`,
  ANV: `Beijing ANTVR Technology`,
  ANW: `Analog Way SAS`,
  ANX: `Acer Netxus`,
  AOA: `AOpen`,
  AOE: `Advanced Optics Electronics`,
  AOL: `America OnLine`,
  AOT: `Alcatel`,
  APC: `American Power Conversion`,
  APD: `AppliAdata`,
  APE: `Alps Alpine`,
  APG: `Horner Electric`,
  API: `Acer America Corp.`,
  APL: `Aplicom Oy`,
  APM: `Applied Memory Tech`,
  APN: `Appian Tech`,
  APP: `Apple Computer`,
  APR: `Aprilia s.p.a.`,
  APS: `Autologic`,
  APT: `Audio Processing Technology`,
  APV: `A+V Link`,
  APX: `AP Designs`,
  ARC: `Alta Research Corporation`,
  ARD: `AREC`,
  ARE: `ICET S.p.A.`,
  ARG: `Argus Electronics`,
  ARI: `Argosy Research`,
  ARK: `Ark Logic`,
  ARL: `Arlotto Comnet`,
  ARM: `Arima`,
  ARO: `Poso International B.V.`,
  ARR: `ARRIS Group`,
  ARS: `Arescom`,
  ART: `Corion Industrial Corporation`,
  ASC: `Ascom Strategic Technology Unit`,
  ASD: `USC Information Sciences Institute`,
  ASE: `AseV Display Labs`,
  ASH: `Ashton Bentley Concepts`,
  ASI: `Ahead Systems`,
  ASK: `Ask A/S`,
  ASL: `AccuScene Corporation`,
  ASM: `ASEM S.p.A.`,
  ASN: `Asante Tech`,
  ASP: `ASP Microelectronics`,
  AST: `AST Research`,
  ASU: `Asuscom Network`,
  ASX: `AudioScience`,
  ASY: `Rockwell Collins / Airshow Systems`,
  ATA: `Allied Telesyn International (Asia) Pte`,
  ATC: `Ably-Tech Corporation`,
  ATD: `Alpha Telecom`,
  ATE: `Innovate`,
  ATH: `Athena Informatica S.r.l.`,
  ATI: `Allied Telesis KK`,
  ATJ: `ArchiTek Corporation`,
  ATK: `Allied Telesyn Int'l`,
  ATL: `Arcus Technology`,
  ATM: `ATM`,
  ATN: `Athena Smartcard Solutions`,
  ATO: `ASTRO DESIGN`,
  ATP: `Alpha-Top Corporation`,
  ATT: `AT&T`,
  ATU: `Avocor Technologies USA`,
  ATV: `Office Depot`,
  ATX: `Athenix Corporation`,
  AUD: `AudioControl`,
  AUG: `August Home`,
  AUI: `Alps Alpine`,
  AUO: `DO NOT USE - AUO`,
  AUR: `Aureal Semiconductor`,
  AUS: `AsusTek Computer`,
  AUT: `Autotime Corporation`,
  AUV: `Auvidea GmbH`,
  AVA: `Avaya Communication`,
  AVC: `Auravision Corporation`,
  AVD: `Avid Electronics Corporation`,
  AVE: `Add Value Enterpises (Asia) Pte`,
  AVG: `Avegant Corporation`,
  AVI: `Nippon Avionics`,
  AVJ: `Atelier Vision Corporation`,
  AVL: `Avalue Technology`,
  AVM: `AVM GmbH`,
  AVN: `Advance Computer Corporation`,
  AVO: `Avocent Corporation`,
  AVR: `AVer Information`,
  AVS: `Avatron Software`,
  AVT: `Avtek (Electronics)`,
  AVV: `SBS Technologies (Canada), Inc. (was Avvida Systems, Inc.)`,
  AVX: `A/Vaux Electronics`,
  AWC: `Access Works Comm`,
  AWL: `Aironet Wireless Communications`,
  AWS: `Wave Systems`,
  AXB: `Adrienne Electronics Corporation`,
  AXC: `Axiomtek`,
  AXE: `Axell Corporation`,
  AXI: `American Magnetics`,
  AXL: `Axel`,
  AXO: `Axonic Labs`,
  AXP: `American Express`,
  AXT: `Axtend Technologies`,
  AXX: `Axxon Computer Corporation`,
  AXY: `AXYZ Automation Services`,
  AYD: `Aydin Displays`,
  AYR: `Airlib`,
  AZH: `Shenzhen three Connaught Information Technology Co., Ltd. (3nod Group)`,
  AZM: `AZ Middelheim - Radiotherapy`,
  AZT: `Aztech Systems`,
  BAC: `Biometric Access Corporation`,
  BAN: `Banyan`,
  BBB: `An-najah University`,
  BBH: `B&Bh`,
  BBL: `Brain Boxes`,
  BBV: `BlueBox Video`,
  BBX: `Black Box Corporation`,
  BCC: `Beaver Computer Corporaton`,
  BCD: `Barco GmbH`,
  BCI: `Broadata Communications`,
  BCK: `Beck GmbH & Co. Elektronik Bauelemente KG`,
  BCM: `Broadcom`,
  BCQ: `Deutsche Telekom Berkom GmbH`,
  BCS: `Booria CAD/CAM systems`,
  BDO: `Brahler ICS`,
  BDR: `Blonder Tongue Labs`,
  BDS: `Barco Display Systems`,
  BEC: `Beckhoff Automation`,
  BEI: `Beckworth Enterprises`,
  BEK: `Beko Elektronik A.S.`,
  BEL: `Beltronic Industrieelektronik GmbH`,
  BEO: `Baug & Olufsen`,
  BFE: `B.F. Engineering Corporation`,
  BFT: `Barnfind Technologies`,
  BGB: `Barco Graphics N.V.`,
  BGT: `Budzetron`,
  BHZ: `BitHeadz`,
  BIA: `Biamp Systems Corporation`,
  BIC: `Big Island Communications`,
  BIG: `Bigscreen`,
  BII: `Boeckeler Instruments`,
  BIL: `Billion Electric Company`,
  BIO: `BioLink Technologies International`,
  BIT: `Bit 3 Computer`,
  BLD: `Bild Innovative Technology`,
  BLI: `Busicom`,
  BLN: `BioLink Technologies`,
  BLP: `Bloomberg L.P.`,
  BMD: `Blackmagic Design`,
  BMI: `Benson Medical Instruments Company`,
  BML: `BIOMED Lab`,
  BMS: `Biomedisys`,
  BNE: `Bull AB`,
  BNK: `Banksia Tech`,
  BNO: `Bang & Olufsen`,
  BNQ: `BenQ Corporation`,
  BNS: `Boulder Nonlinear Systems`,
  BOB: `Rainy Orchard`,
  BOE: `BOE Display Technology`,
  BOI: `Ningbo Boigle Digital Technology`,
  BOS: `BOS`,
  BPD: `Micro Solutions`,
  BPS: `Barco, N.V.`,
  BPU: `Best Power`,
  BRA: `Braemac`,
  BRC: `BARC`,
  BRG: `Bridge Information`,
  BRI: `Boca Research`,
  BRL: `Brainlab AG`,
  BRM: `Braemar`,
  BRO: `Brother Industries`,
  BSE: `Bose Corporation`,
  BSG: `Robert Bosch GmbH`,
  BSL: `Biomedical Systems Laboratory`,
  BSN: `BrightSign`,
  BST: `BodySound Technologies`,
  BTC: `Bit 3 Computer`,
  BTE: `Brilliant Technology`,
  BTF: `Bitfield Oy`,
  BTI: `BusTech`,
  BTO: `BioTao`,
  BUF: `Yasuhiko Shirai Melco`,
  BUG: `B.U.G.`,
  BUJ: `ATI Tech`,
  BUL: `Bull`,
  BUR: `B&R Industrial Automation GmbH`,
  BUS: `BusTek`,
  BUT: `21st Century Entertainment`,
  BWK: `Bitworks`,
  BXE: `Buxco Electronics`,
  BYD: `byd:sign Corporation`,
  CAA: `Castles Automation`,
  CAC: `CA & F Elettronica`,
  CAG: `CalComp`,
  CAI: `Canon`,
  CAL: `Acon`,
  CAM: `Cambridge Audio`,
  CAN: `Canopus Company`,
  CAR: `Cardinal Company`,
  CAS: `Casio Computer`,
  CAT: `Consultancy in Advanced Technology`,
  CAV: `Cavium Networks`,
  CBI: `ComputerBoards`,
  CBR: `Cebra Tech A/S`,
  CBT: `Cabletime`,
  CBX: `Cybex Computer Products Corporation`,
  CCC: `C-Cube Microsystems`,
  CCI: `Cache`,
  CCJ: `CONTEC`,
  CCL: `CCL/ITRI`,
  CCP: `Capetronic USA`,
  CDC: `Core Dynamics Corporation`,
  CDD: `Convergent Data Devices`,
  CDE: `Colin.de`,
  CDG: `Christie Digital Systems`,
  CDI: `Concept Development`,
  CDK: `Cray Communications`,
  CDN: `Codenoll Technical Corporation`,
  CDP: `CalComp`,
  CDS: `Computer Diagnostic Systems`,
  CDT: `IBM Corporation`,
  CDV: `Convergent Design`,
  CEA: `Consumer Electronics Association`,
  CEC: `Chicony Electronics Company`,
  CED: `Cambridge Electronic Design`,
  CEF: `Cefar Digital Vision`,
  CEI: `Crestron Electronics`,
  CEM: `MEC Electronics GmbH`,
  CEN: `Centurion Technologies P/L`,
  CEP: `C-DAC`,
  CER: `Ceronix`,
  CET: `TEC Corporation`,
  CFG: `Atlantis`,
  CFR: `Meta View`,
  CGA: `Chunghwa Picture Tubes`,
  CGS: `Chyron Corp`,
  CGT: `congatec AG`,
  CHA: `Chase Research PLC`,
  CHD: `ChangHong Electric`,
  CHE: `Acer`,
  CHG: `Sichuan Changhong Electric CO`,
  CHI: `Chrontel`,
  CHL: `Chloride-R&D`,
  CHM: `CHIC TECHNOLOGY CORP.`,
  CHO: `Sichuang Changhong Corporation`,
  CHP: `CH Products`,
  CHR: `christmann informationstechnik + medien GmbH & Co. KG`,
  CHS: `Agentur Chairos`,
  CHT: `Chunghwa Picture Tubes`,
  CHY: `Cherry GmbH`,
  CIC: `Comm. Intelligence Corporation`,
  CID: `Indicates an identity defined by CTS/DID Standards other than EDID`,
  CIE: `Convergent Engineering`,
  CII: `Cromack Industries`,
  CIL: `Citicom Infotech Private`,
  CIN: `Citron GmbH`,
  CIP: `Ciprico`,
  CIR: `Cirrus Logic`,
  CIS: `Cisco Systems`,
  CIT: `Citifax`,
  CKC: `The Concept Keyboard Company`,
  CKJ: `Carina System`,
  CLA: `Clarion Company`,
  CLD: `Commat Ltd.`,
  CLE: `Classe Audio`,
  CLG: `CoreLogic`,
  CLI: `Cirrus Logic`,
  CLM: `CrystaLake Multimedia`,
  CLO: `Clone Computers`,
  CLR: `Clover Electronics`,
  CLT: `Automated Computer Control Systems`,
  CLV: `Clevo Company`,
  CLX: `CardLogix`,
  CMC: `CMC`,
  CMD: `Colorado MicroDisplay`,
  CMG: `Chenming Mold Ind. Corp.`,
  CMI: `C-Media Electronics`,
  CMK: `Comark`,
  CMM: `Comtime GmbH`,
  CMN: `Chimei Innolux Corporation`,
  CMO: `Chi Mei Optoelectronics corp.`,
  CMR: `Cambridge Research Systems`,
  CMS: `CompuMaster S.r.l.`,
  CMX: `Comex Electronics AB`,
  CNB: `American Power Conversion`,
  CNC: `Alvedon Computers`,
  CND: `Micro-Star Int'l`,
  CNE: `Cine-tal`,
  CNI: `Connect Int'l A/S`,
  CNN: `Canon`,
  CNT: `COINT Multimedia Systems`,
  COB: `COBY Electronics`,
  COD: `CODAN Pty.`,
  COI: `Codec`,
  COL: `Rockwell Collins`,
  COM: `Comtrol Corporation`,
  CON: `Contec Company`,
  COO: `Coolux GmbH`,
  COR: `Corollary`,
  COS: `CoStar Corporation`,
  COT: `Core Technology`,
  COW: `Polycow Productions`,
  COX: `Comrex`,
  CPC: `Ciprico`,
  CPD: `CompuAdd`,
  CPI: `Computer Peripherals`,
  CPL: `Compal Electronics`,
  CPM: `Capella Microsystems`,
  CPP: `Compound Photonics`,
  CPQ: `Compaq Computer Company`,
  CPT: `cPATH`,
  CPX: `Powermatic Data Systems`,
  CRA: `Craltech Electronica, S.L.`,
  CRC: `CONRAC GmbH`,
  CRD: `Cardinal Technical`,
  CRE: `Creative Labs`,
  CRH: `Contemporary Research Corp.`,
  CRI: `Crio`,
  CRL: `Creative Logic`,
  CRM: `Corsair Memory`,
  CRN: `Cornerstone Imaging`,
  CRO: `Extraordinary Technologies PTY`,
  CRQ: `Cirque Corporation`,
  CRS: `Crescendo Communication`,
  CRV: `Cerevo`,
  CRW: `Cammegh`,
  CRX: `Cyrix Corporation`,
  CSB: `Transtex SA`,
  CSC: `Crystal Semiconductor`,
  CSD: `Cresta Systems`,
  CSE: `Concept Solutions & Engineering`,
  CSI: `Cabletron System`,
  CSL: `Cloudium Systems`,
  CSM: `Cosmic Engineering`,
  CSO: `California Institute of Technology`,
  CSS: `CSS Laboratories`,
  CST: `CSTI`,
  CSW: `China Star Optoelectronics Technology`,
  CTA: `CoSystems`,
  CTC: `CTC Communication Development Company`,
  CTE: `Chunghwa Telecom`,
  CTL: `Creative Technology`,
  CTM: `Computerm Corporation`,
  CTN: `Computone Products`,
  CTP: `Computer Technology Corporation`,
  CTR: `Control4 Corporation`,
  CTS: `Comtec Systems`,
  CTX: `Creatix Polymedia GmbH`,
  CUB: `Cubix Corporation`,
  CUK: `Calibre UK`,
  CVA: `Covia`,
  CVI: `Colorado Video`,
  CVP: `Chromatec Video Products`,
  CVS: `Clarity Visual Systems`,
  CWC: `Curtiss-Wright Controls`,
  CWR: `Connectware`,
  CXT: `Conexant Systems`,
  CYB: `CyberVision`,
  CYC: `Cylink Corporation`,
  CYD: `Cyclades Corporation`,
  CYL: `Cyberlabs`,
  CYP: `Cypress Semiconductor Corporation`,
  CYT: `Cytechinfo`,
  CYV: `Cyviz AS`,
  CYW: `Cyberware`,
  CYX: `Cyrix Corporation`,
  CZC: `Shenzhen ChuangZhiCheng Technology`,
  CZE: `Carl Zeiss AG`,
  DAC: `Digital Acoustics Corporation`,
  DAE: `Digatron Industrie Elektronik GmbH`,
  DAI: `DAIS SET`,
  DAK: `Daktronics`,
  DAL: `Digital Audio Labs`,
  DAN: `Danelec Marine A/S`,
  DAS: `DAVIS AS`,
  DAT: `Datel`,
  DAU: `Daou Tech`,
  DAV: `Davicom Semiconductor`,
  DAW: `DA2 Technologies`,
  DAX: `Data Apex`,
  DBD: `Diebold`,
  DBI: `DigiBoard`,
  DBK: `Databook`,
  DBL: `Doble Engineering Company`,
  DBN: `DB Networks`,
  DCA: `Digital Communications Association`,
  DCC: `Dale Computer Corporation`,
  DCD: `Datacast`,
  DCE: `dSPACE GmbH`,
  DCI: `Concepts`,
  DCL: `Dynamic Controls`,
  DCM: `DCM Data Products`,
  DCO: `Dialogue Technology Corporation`,
  DCR: `Decros`,
  DCS: `Diamond Computer Systems`,
  DCT: `Dancall Telecom A/S`,
  DCV: `Datatronics Technology`,
  DDA: `DA2 Technologies Corporation`,
  DDD: `Danka Data Devices`,
  DDE: `Datasat Digital Entertainment`,
  DDI: `Data Display AG`,
  DDS: `Barco, N.V.`,
  DDT: `Datadesk Technologies`,
  DDV: `Delta Information Systems`,
  DEC: `Digital Equipment Corporation`,
  DEF: `DEIF A/S`,
  DEI: `Deico Electronics`,
  DEL: `Dell`,
  DEM: `DemoPad Software`,
  DEN: `Densitron Computers`,
  DEX: `IDEX Displays`,
  DFI: `DFI`,
  DFK: `SharkTec A/S`,
  DFT: `DEI Holdings dba Definitive Technology`,
  DGA: `Digiital Arts`,
  DGC: `Data General Corporation`,
  DGI: `DIGI International`,
  DGK: `DugoTech`,
  DGP: `Digicorp European sales S.A.`,
  DGS: `Diagsoft`,
  DGT: `Dearborn Group Technology`,
  DHD: `Dension Audio Systems`,
  DHP: `DH Print`,
  DHQ: `Quadram`,
  DHT: `Projectavision`,
  DIA: `Diadem`,
  DIG: `Digicom S.p.A.`,
  DII: `Dataq Instruments`,
  DIM: `dPict Imaging`,
  DIN: `Daintelecom`,
  DIS: `Diseda S.A.`,
  DIT: `Dragon Information Technology`,
  DJE: `Capstone Visua lProduct Development`,
  DJP: `Maygay Machines`,
  DKY: `Datakey`,
  DLB: `Dolby Laboratories`,
  DLC: `Diamond Lane Comm. Corporation`,
  DLD: `Delem`,
  DLG: `Digital-Logic GmbH`,
  DLK: `D-Link Systems`,
  DLL: `Dell`,
  DLM: `DLOGIC`,
  DLO: `Shenzhen Dlodlo Technologies`,
  DLT: `Digitelec Informatique Park Cadera`,
  DMB: `Digicom Systems`,
  DMC: `Dune Microsystems Corporation`,
  DMG: `Monoprice`,
  DMM: `Dimond Multimedia Systems`,
  DMN: `Dimension Engineering`,
  DMO: `Data Modul AG`,
  DMP: `D&M Holdings Inc, Professional Business Company`,
  DMS: `DOME imaging systems`,
  DMT: `Distributed Management Task Force, Inc. (DMTF)`,
  DMV: `NDS`,
  DNA: `DNA Enterprises`,
  DNG: `Apache Micro Peripherals`,
  DNI: `Deterministic Networks`,
  DNT: `Dr. Neuhous Telekommunikation GmbH`,
  DNV: `DiCon`,
  DOL: `Dolman Technologies Group`,
  DOM: `Dome Imaging Systems`,
  DON: `Denon`,
  DOT: `Dotronic Mikroelektronik GmbH`,
  DPA: `DigiTalk Pro AV`,
  DPC: `Delta Electronics`,
  DPH: `Delphi Automotive LLP`,
  DPI: `DocuPoint`,
  DPL: `Digital Projection`,
  DPM: `ADPM Synthesis sas`,
  DPN: `Shanghai Lexiang Technology`,
  DPS: `Digital Processing Systems`,
  DPT: `DPT`,
  DPX: `dpiX`,
  DQB: `Datacube`,
  DRB: `Dr. Bott KG`,
  DRC: `Data Ray Corp.`,
  DRD: `DIGITAL REFLECTION`,
  DRI: `Data Race`,
  DRS: `DRS Defense Solutions`,
  DSA: `Display Solution AG`,
  DSD: `DS Multimedia Pte`,
  DSG: `Disguise Technologies`,
  DSI: `Digitan Systems`,
  DSJ: `VR Technology Holdings`,
  DSM: `DSM Digital Services GmbH`,
  DSP: `Domain Technology`,
  DTA: `Deltatec`,
  DTC: `DTC Tech Corporation`,
  DTE: `Dimension Technologies`,
  DTI: `Diversified Technology`,
  DTK: `Dynax Electronics (HK)`,
  DTL: `e-Net`,
  DTM: `Daten Tecnologia`,
  DTN: `Datang  Telephone Co`,
  DTO: `Deutsche Thomson OHG`,
  DTT: `Design & Test Technology`,
  DTX: `Data Translation`,
  DUA: `Dosch & Amand GmbH & Company KG`,
  DUN: `NCR Corporation`,
  DVD: `Dictaphone Corporation`,
  DVL: `Devolo AG`,
  DVS: `Digital Video System`,
  DVT: `Data Video`,
  DWE: `Daewoo Electronics Company`,
  DXC: `Digipronix Control Systems`,
  DXD: `Decimator Design`,
  DXL: `Dextera Labs`,
  DXN: `Dixon Technologies (India)`,
  DXP: `Data Expert Corporation`,
  DXS: `Signet`,
  DYC: `Dycam`,
  DYM: `Dymo-CoStar Corporation`,
  DYN: `Askey Computer Corporation`,
  DYX: `Dynax Electronics (HK)`,
  EAC: `Emotiva Audio Corp.`,
  EAG: `ELTEC Elektronik AG`,
  EAS: `Evans and Sutherland Computer`,
  EBH: `Data Price Informatica`,
  EBS: `EBS Euchner Büro- und Schulsysteme GmbH`,
  EBT: `Hualong Technology`,
  ECA: `Electro Cam Corp.`,
  ECC: `ESSential Comm. Corporation`,
  ECH: `EchoStar Corporation`,
  ECI: `Enciris Technologies`,
  ECK: `Eugene Chukhlomin Sole Proprietorship, d.b.a.`,
  ECL: `Excel Company`,
  ECM: `E-Cmos Tech Corporation`,
  ECO: `Echo Speech Corporation`,
  ECP: `Elecom Company`,
  ECS: `Elitegroup Computer Systems Company`,
  ECT: `Enciris Technologies`,
  EDC: `e.Digital Corporation`,
  EDG: `Electronic-Design GmbH`,
  EDI: `Edimax Tech. Company`,
  EDM: `EDMI`,
  EDT: `Emerging Display Technologies Corp`,
  EEE: `ET&T Technology Company`,
  EEH: `EEH Datalink GmbH`,
  EEI: `Elaraby Company for Engineering Industries`,
  EEP: `E.E.P.D. GmbH`,
  EES: `EE Solutions`,
  EGA: `Elgato Systems`,
  EGD: `EIZO GmbH Display Technologies`,
  EGL: `Eagle Technology`,
  EGN: `Egenera`,
  EGO: `Ergo Electronics`,
  EHJ: `Epson Research`,
  EHN: `Enhansoft`,
  EIC: `Eicon Technology Corporation`,
  EIN: `Elegant Invention`,
  EKA: `MagTek`,
  EKC: `Eastman Kodak Company`,
  EKS: `EKSEN YAZILIM`,
  ELA: `ELAD S.r.l.`,
  ELC: `Electro Scientific Ind`,
  ELD: `Express Luck`,
  ELE: `Elecom Company`,
  ELG: `Elmeg GmbH Kommunikationstechnik`,
  ELI: `Edsun Laboratories`,
  ELL: `Electrosonic`,
  ELM: `Elmic Systems`,
  ELO: `Elo TouchSystems`,
  ELS: `ELSA GmbH`,
  ELT: `Element Labs`,
  ELU: `Express Industrial`,
  ELX: `Elonex PLC`,
  EMB: `Embedded computing`,
  EMC: `eMicro Corporation`,
  EMD: `Embrionix Design`,
  EME: `Emine Technology Company`,
  EMG: `EMG Consultants`,
  EMI: `Ex Machina`,
  EMK: `Emcore Corporation`,
  EMO: `Elmo Company`,
  EMR: `ICC Intelligent Platforms GmbH`,
  EMU: `Emulex Corporation`,
  ENC: `Eizo Nanao Corporation`,
  END: `ENIDAN Technologies`,
  ENE: `ENE Technology`,
  ENI: `Efficient Networks`,
  ENS: `Ensoniq Corporation`,
  ENT: `Enterprise Comm. & Computing`,
  EON: `Eon Instrumentation`,
  EPC: `Empac`,
  EPH: `Epiphan Systems`,
  EPI: `Envision Peripherals`,
  EPN: `EPiCON`,
  EPS: `KEPS`,
  EQP: `Equipe Electronics`,
  EQX: `Equinox Systems`,
  ERG: `Ergo System`,
  ERI: `Ericsson Mobile Communications AB`,
  ERN: `Ericsson`,
  ERP: `Euraplan GmbH`,
  ERS: `Eizo Rugged Solutions`,
  ERT: `Escort Insturments Corporation`,
  ESA: `Elbit Systems of America`,
  ESB: `ScioTeq`,
  ESC: `Eden Sistemas de Computacao S/A`,
  ESD: `Ensemble Designs`,
  ESG: `ELCON Systemtechnik GmbH`,
  ESI: `Extended Systems`,
  ESK: `ES&S`,
  ESL: `Esterline Technologies`,
  ESN: `eSATURNUS`,
  ESS: `ESS Technology`,
  EST: `Embedded Solution Technology`,
  ESY: `E-Systems`,
  ETC: `Everton Technology Company`,
  ETD: `Elan Microelectronics Corporation`,
  ETG: `Eizo Technologies GmbH`,
  ETH: `Etherboot Project`,
  ETI: `Eclipse Tech`,
  ETK: `eTEK Labs`,
  ETL: `Evertz Microsystems`,
  ETS: `Electronic Trade Solutions`,
  ETT: `E-Tech`,
  EUT: `Ericsson Mobile Networks B.V.`,
  EVE: `Advanced Micro Peripherals`,
  EVI: `eviateg GmbH`,
  EVP: `EverPro Technologies Company`,
  EVX: `Everex`,
  EXA: `Exabyte`,
  EXC: `Excession Audio`,
  EXI: `Exide Electronics`,
  EXN: `RGB Systems, Inc. dba Extron Electronics`,
  EXP: `Data Export Corporation`,
  EXR: `Explorer`,
  EXT: `Exatech Computadores & Servicos Ltda`,
  EXX: `Exxact GmbH`,
  EXY: `Exterity`,
  EYE: `EyeVis GmbH`,
  EYF: `eyefactive GmbH`,
  EZE: `EzE Technologies`,
  EZP: `Storm Technology`,
  FAN: `Fantalooks`,
  FAR: `Farallon Computing`,
  FBI: `Interface Corporation`,
  FCB: `Furukawa Electric Company`,
  FCG: `First International Computer`,
  FCS: `Focus Enhancements`,
  FDC: `Future Domain`,
  FDD: `Forth Dimension Displays`,
  FDI: `Future Designs`,
  FDT: `Fujitsu Display Technologies Corp.`,
  FDX: `Findex`,
  FEC: `Furuno Electric`,
  FEL: `Fellowes & Questec`,
  FEN: `Fen Systems`,
  FER: `Ferranti Int'L`,
  FFC: `Fujifilm Corporation`,
  FFI: `Fairfield Industries`,
  FGD: `Lisa Draexlmaier GmbH`,
  FGL: `Fujitsu General Limited.`,
  FHL: `FHLP`,
  FIC: `Formosa Industrial Computing`,
  FIL: `Forefront Int'l`,
  FIN: `Finecom`,
  FIR: `Chaplet Systems`,
  FIS: `FLY-IT Simulators`,
  FIT: `Feature Integration Technology`,
  FJC: `FCL Components`,
  FJS: `Fujitsu Spain`,
  FJT: `F.J. Tieman BV`,
  FLE: `ADTI Media`,
  FLI: `Faroudja Laboratories`,
  FLY: `Butterfly Communications`,
  FMA: `Fast Multimedia AG`,
  FMC: `Ford Microelectronics`,
  FMI: `Fellowes`,
  FML: `Fujitsu Microelect`,
  FMZ: `Formoza-Altair`,
  FNC: `Fanuc`,
  FNI: `Funai Electric`,
  FOA: `FOR-A Company`,
  FOK: `Fokus Technologies GmbH`,
  FOS: `Foss Tecator`,
  FOV: `FOVE`,
  FOX: `Foxconn`,
  FPC: `Fingerprint Cards AB`,
  FPE: `Fujitsu Peripherals`,
  FPS: `Deltec Corporation`,
  FPX: `Cirel Systemes`,
  FRC: `Force Computers`,
  FRD: `Freedom Scientific BLV`,
  FRE: `Forvus Research`,
  FRI: `Fibernet Research`,
  FRO: `FARO Technologies`,
  FRS: `South Mountain Technologies`,
  FSC: `Future Systems Consulting KK`,
  FSI: `Fore Systems`,
  FST: `Modesto PC`,
  FTC: `Futuretouch Corporation`,
  FTE: `Frontline Test Equipment`,
  FTG: `FTG Data Systems`,
  FTI: `FastPoint Technologies`,
  FTL: `Fujitsu Ten`,
  FTN: `Fountain Technologies`,
  FTR: `Mediasonic`,
  FTS: `FocalTech Systems`,
  FTW: `MindTribe Product Engineering`,
  FUJ: `Fujitsu`,
  FUL: `Fun Technology Innovation`,
  FUN: `Sisel Muhendislik`,
  FUS: `Fujitsu Siemens Computers GmbH`,
  FVC: `First Virtual Corporation`,
  FVX: `C-C-C Group Plc`,
  FWA: `Attero Tech`,
  FWR: `Flat Connections`,
  FXX: `Fuji Xerox`,
  FZC: `Founder Group Shenzhen`,
  FZI: `FZI Forschungszentrum Informatik`,
  GAC: `GreenArrays`,
  GAG: `Gage Applied Sciences`,
  GAL: `Galil Motion Control`,
  GAU: `Gaudi`,
  GBT: `GIGA-BYTE TECHNOLOGY`,
  GCC: `GCC Technologies`,
  GCI: `Gateway Comm.`,
  GCS: `Grey Cell Systems`,
  GDC: `General Datacom`,
  GDI: `G. Diehl ISDN GmbH`,
  GDS: `GDS`,
  GDT: `Vortex Computersysteme GmbH`,
  GEC: `Gechic Corporation`,
  GED: `General Dynamics C4 Systems`,
  GEF: `GE Fanuc Embedded Systems`,
  GEH: `Abaco Systems`,
  GEM: `Gem Plus`,
  GEN: `Genesys ATE`,
  GEO: `GEO Sense`,
  GER: `Germaneers GmbH`,
  GES: `GES Singapore Pte`,
  GET: `Getac Technology Corporation`,
  GFM: `GFMesstechnik GmbH`,
  GFN: `Gefen`,
  GGL: `Google`,
  GGT: `G2Touch Korea`,
  GIC: `General Inst. Corporation`,
  GIM: `Guillemont International`,
  GIP: `GI Provision`,
  GIS: `AT&T Global Info Solutions`,
  GJN: `Grand Junction Networks`,
  GLD: `Goldmund - Digital Audio SA`,
  GLE: `AD electronics`,
  GLM: `Genesys Logic`,
  GLS: `Gadget Labs`,
  GMK: `GMK Electronic Design GmbH`,
  GML: `General Information Systems`,
  GMM: `GMM Research`,
  GMN: `Gemini 2000`,
  GMX: `GMX`,
  GND: `Gennum Corporation`,
  GNN: `GN Nettest`,
  GNZ: `Gunze`,
  GOE: `Goepel Electronic GmbH`,
  GPR: `GoPro`,
  GRA: `Graphica Computer`,
  GRE: `Gold Rain Enterprises Corp.`,
  GRH: `Granch`,
  GRM: `Garmin International`,
  GRV: `Advanced Gravis`,
  GRY: `Robert Gray Company`,
  GSB: `Nippondenchi Co.`,
  GSC: `General Standards Corporation`,
  GSM: `LG Electronics Inc. (GoldStar Technology, Inc.)`,
  GSN: `Grandstream Networks`,
  GST: `Graphic SystemTechnology`,
  GSY: `Grossenbacher Systeme AG`,
  GTC: `Graphtec Corporation`,
  GTI: `Goldtouch`,
  GTK: `G-Tech Corporation`,
  GTM: `Garnet System Company`,
  GTS: `Geotest Marvin Test Systems`,
  GTT: `General Touch Technology`,
  GUD: `Guntermann & Drunck GmbH`,
  GUP: `GoUp`,
  GUZ: `Guzik Technical Enterprises`,
  GVC: `GVC Corporation`,
  GVL: `Global Village Communication`,
  GVS: `GVision`,
  GWI: `GW Instruments`,
  GWK: `Gateworks Corporation`,
  GWY: `Gateway 2000`,
  GXL: `Galaxy Microsystems`,
  GZE: `Gunze`,
  HAE: `Haider electronics`,
  HAI: `Haivision Systems`,
  HAL: `Halberthal`,
  HAN: `Hanchang System Corporation`,
  HAR: `Harris Corporation`,
  HAY: `Hayes Microcomputer Products`,
  HCA: `DAT`,
  HCE: `Hitachi Consumer Electronics`,
  HCL: `HCL America`,
  HCM: `HCL Peripherals`,
  HCP: `Hitachi Computer Products`,
  HCW: `Hauppauge Computer Works`,
  HDC: `HardCom Elektronik & Datateknik`,
  HDI: `HD-INFO d.o.o.`,
  HDV: `Holografika kft.`,
  HEC: `Hisense Electric`,
  HEL: `Hitachi Micro Systems Europe`,
  HER: `Ascom Business Systems`,
  HET: `HETEC Datensysteme GmbH`,
  HHC: `Hirakawa Hewtech Corp.`,
  HHI: `Fraunhofer Heinrich-Hertz-Institute`,
  HHT: `Hitevision Group`,
  HIB: `Hibino Corporation`,
  HIC: `Hitachi Information Technology`,
  HII: `Harman International Industries`,
  HIK: `Hikom`,
  HIL: `Hilevel Technology`,
  HIQ: `Hyundai ImageQuest`,
  HIS: `Hope Industrial Systems`,
  HIT: `Hitachi America`,
  HJI: `Harris & Jeffries`,
  HKA: `Honko Mfg.`,
  HKC: `HKC Overseas`,
  HKG: `Josef Heim KG`,
  HLG: `China Hualu Group`,
  HMC: `Hualon Microelectric Corporation`,
  HMK: `hmk Daten-System-Technik GmbH`,
  HMX: `HUMAX`,
  HNM: `HONOR Device`,
  HNS: `Hughes Network Systems`,
  HOB: `HOB Electronic GmbH`,
  HOE: `Hosiden Corporation`,
  HOL: `Holoeye Photonics AG`,
  HON: `Sonitronix`,
  HPA: `Zytor Communications`,
  HPC: `Hewlett-Packard`,
  HPD: `Hewlett Packard`,
  HPE: `Hewlett Packard Enterprise`,
  HPI: `Headplay`,
  HPK: `Hamamatsu Photonics K.K.`,
  HPN: `HP`,
  HPQ: `Hewlett-Packard`,
  HPR: `H.P.R. Electronics GmbH`,
  HRC: `Hercules`,
  HRE: `Qingdao Haier Electronics`,
  HRI: `Hall Research`,
  HRL: `Herolab GmbH`,
  HRS: `Harris Semiconductor`,
  HRT: `Hercules`,
  HSC: `Hagiwara Sys-Com Company`,
  HSD: `HannStar Display Corp`,
  HSM: `AT&T Microelectronics`,
  HSN: `Hansung`,
  HSP: `HannStar Display Corp`,
  HST: `Horsent Technology`,
  HTC: `Hitachi`,
  HTI: `Hampshire Company`,
  HTK: `Holtek Microelectronics`,
  HTL: `HTBLuVA Mödling`,
  HTR: `Shenzhen ZhuoYi HengTong Computer Technology`,
  HTX: `Hitex Systementwicklung GmbH`,
  HUB: `GAI-Tronics, A Hubbell Company`,
  HUK: `Hoffmann + Krippner GmbH`,
  HUM: `IMP Electronics`,
  HVR: `HTC Corportation`,
  HWA: `Harris Canada`,
  HWC: `DBA Hans Wedemeyer`,
  HWD: `Highwater Designs`,
  HWP: `Hewlett Packard`,
  HWV: `Huawei Technologies`,
  HXM: `Hexium`,
  HYC: `Hypercope GmbH Aachen`,
  HYD: `Hydis Technologies Co.`,
  HYL: `Shanghai Chai Ming Huang Info&Tech Co`,
  HYO: `HYC`,
  HYP: `Hyphen`,
  HYR: `Hypertec`,
  HYT: `Heng Yu Technology (HK)`,
  HYV: `Hynix Semiconductor`,
  IAD: `IAdea Corporation`,
  IAF: `Institut fur angewandte Funksystemtechnik GmbH`,
  IAI: `Integration Associates`,
  IAT: `IAT Germany GmbH`,
  IBC: `Integrated Business Systems`,
  IBI: `Inbine Co.`,
  IBM: `IBM`,
  IBP: `IBP Instruments GmbH`,
  IBR: `IBR GmbH`,
  ICA: `ICA`,
  ICC: `BICC Data Networks`,
  ICD: `ICD`,
  ICE: `IC Ensemble`,
  ICI: `Infotek Communication`,
  ICM: `Intracom SA`,
  ICN: `Sanyo Icon`,
  ICO: `Intel Corp`,
  ICP: `ICP Electronics, Inc. / iEi Technology Corp.`,
  ICR: `Icron`,
  ICS: `Integrated Circuit Systems`,
  ICV: `Inside Contactless`,
  ICX: `ICCC A/S`,
  IDC: `International Datacasting Corporation`,
  IDE: `IDE Associates`,
  IDK: `IDK Corporation`,
  IDN: `Idneo Technologies`,
  IDO: `IDEO Product Development`,
  IDP: `Integrated Device Technology`,
  IDS: `Interdigital Sistemas de Informacao`,
  IDT: `International Display Technology`,
  IDX: `IDEXX Labs`,
  IEC: `Interlace Engineering Corporation`,
  IEE: `IEE`,
  IEI: `Interlink Electronics`,
  IFS: `InFocus Systems`,
  IFT: `Informtech`,
  IFX: `Infineon Technologies AG`,
  IFZ: `Infinite Z`,
  IGC: `Intergate`,
  IGM: `IGM Communi`,
  IHE: `InHand Electronics`,
  IIC: `ISIC Innoscan Industrial Computers A/S`,
  III: `Intelligent Instrumentation`,
  IIN: `IINFRA`,
  IIT: `Informatik Information Technologies`,
  IKE: `Ikegami Tsushinki`,
  IKS: `Ikos Systems`,
  ILC: `Image Logic Corporation`,
  ILS: `Innotech Corporation`,
  IMA: `Imagraph`,
  IMB: `ART S.r.l.`,
  IMC: `IMC Networks`,
  IMD: `ImasDe Canarias S.A.`,
  IME: `Imagraph`,
  IMF: `Immersive Audio Technologies France`,
  IMG: `IMAGENICS`,
  IMI: `International Microsystems`,
  IMM: `Immersion Corporation`,
  IMN: `Impossible Production`,
  IMP: `Impinj`,
  IMT: `Inmax Technology Corporation`,
  IMX: `Arpara Technology`,
  INA: `Inventec Corporation`,
  INC: `Home Row`,
  IND: `ILC`,
  INE: `Inventec Electronics (M) Sdn. Bhd.`,
  INF: `Inframetrics`,
  ING: `Integraph Corporation`,
  INI: `Initio Corporation`,
  INK: `Indtek`,
  INL: `InnoLux Display Corporation`,
  INM: `InnoMedia`,
  INN: `Innovent Systems`,
  INO: `Innolab Pte`,
  INP: `Interphase Corporation`,
  INS: `Ines GmbH`,
  INT: `Interphase Corporation`,
  inu: `Inovatec S.p.A.`,
  INV: `Inviso`,
  INX: `Communications Supply Corporation (a division of WESCO)`,
  INZ: `Best Buy`,
  IOA: `CRE Technology Corporation`,
  IOC: `Guangxi Century Innovation Display Electronics`,
  IOD: `I-O Data Device`,
  IOM: `Iomega`,
  ION: `Inside Out Networks`,
  IOS: `i-O Display System`,
  IOT: `I/OTech`,
  IPC: `IPC Corporation`,
  IPD: `Industrial Products Design`,
  IPI: `Intelligent Platform Management Interface (IPMI) forum (Intel, HP, NEC, Dell)`,
  IPM: `IPM Industria Politecnica Meridionale SpA`,
  IPN: `Performance Technologies`,
  IPP: `IP Power Technologies GmbH`,
  IPQ: `IP3 Technology`,
  IPR: `Ithaca Peripherals`,
  IPS: `IPS, Inc. (Intellectual Property Solutions, Inc.)`,
  IPT: `International Power Technologies`,
  IPW: `IPWireless`,
  IQI: `IneoQuest Technologies`,
  IQT: `ImageQuest`,
  IRD: `Irdata`,
  ISA: `Symbol Technologies`,
  ISC: `Id3 Semiconductors`,
  ISG: `Insignia Solutions`,
  ISI: `Interface Solutions`,
  ISL: `Isolation Systems`,
  ISM: `Image Stream Medical`,
  ISP: `IntreSource Systems Pte`,
  ISR: `INSIS`,
  ISS: `ISS`,
  IST: `Intersolve Technologies`,
  ISY: `International Integrated Systems, Inc. (IISI)`,
  ITA: `Itausa Export North America`,
  ITC: `Intercom`,
  ITD: `Internet Technology Corporation`,
  ITE: `Integrated Tech Express`,
  ITI: `VanErum Group`,
  ITK: `ITK Telekommunikation AG`,
  ITL: `Inter-Tel`,
  ITM: `ITM`,
  ITN: `The NTI Group`,
  ITP: `IT-PRO Consulting und Systemhaus GmbH`,
  ITR: `Infotronic America`,
  ITS: `IDTECH`,
  ITT: `I&T Telecom.`,
  ITX: `Integrated Technology Express`,
  IUC: `ICSL`,
  IVI: `Intervoice`,
  IVM: `Iiyama North America`,
  IVO: `InfoVision Optoelectronics (Kunshan) Co., Ltd China`,
  IVR: `Inlife-Handnet`,
  IVS: `Intevac Photonics`,
  IWR: `Icuiti Corporation`,
  IWX: `Intelliworxx`,
  IXD: `Intertex Data AB`,
  IXN: `Shenzhen Inet Mobile Internet Technology`,
  JAC: `Astec`,
  JAE: `Japan Aviation Electronics Industry`,
  JAS: `Janz Automationssysteme AG`,
  JAT: `Jaton Corporation`,
  JAZ: `Carrera Computer`,
  JCE: `Jace Tech`,
  JDI: `Japan Display`,
  JDL: `Japan Digital Laboratory`,
  JEM: `Japan E.M.Solutions`,
  JEN: `N-Vision`,
  JET: `Jet Power Technology`,
  JFX: `Jones Futurex`,
  JGD: `University College`,
  JIC: `Jaeik Information & Communication`,
  JKC: `JVC KENWOOD Corporation`,
  JLK: `Unionman Technology`,
  JMT: `Micro Technical Company`,
  JPC: `JPC Technology`,
  JPW: `Wallis Hamilton Industries`,
  JQE: `CNet Technical`,
  JSD: `JS DigiTech`,
  JSI: `Jupiter Systems`,
  JSK: `Sanken Electric`,
  JTS: `JS Motorsports`,
  JTY: `Jetway Security Micro`,
  JUK: `Janich & Klass Computertechnik GmbH`,
  JUP: `Jupiter Systems`,
  JVC: `JVC`,
  JWD: `Video International`,
  JWL: `Jewell Instruments`,
  JWS: `JWSpencer & Co.`,
  JWY: `Jetway Information`,
  KAR: `Karna`,
  KBI: `Kidboard`,
  KBL: `Kobil Systems GmbH`,
  KCD: `Chunichi Denshi`,
  KCL: `Keycorp`,
  KDE: `KDE`,
  KDK: `Kodiak Tech`,
  KDM: `Korea Data Systems`,
  KDS: `KDS USA`,
  KDT: `KDDI Technology Corporation`,
  KEC: `Kyushu Electronics Systems`,
  KEM: `Kontron Embedded Modules GmbH`,
  KES: `Kesa Corporation`,
  KEU: `Kontron Europe GmbH`,
  KEY: `Key Tech`,
  KFC: `SCD Tech`,
  KFE: `Komatsu Forest`,
  KFX: `Kofax Image Products`,
  KGI: `Klipsch Group`,
  KGL: `Keisoku Giken`,
  KGN: `Kogan Australia`,
  KIO: `Kionix`,
  KIS: `KiSS Technology A/S`,
  KLT: `Colorlight`,
  KMC: `Mitsumi Company`,
  KME: `KIMIN Electronics`,
  KML: `Kensington Microware`,
  KMR: `Kramer Electronics Ltd. International`,
  KNC: `Konica corporation`,
  KNX: `Nutech Marketing PTL`,
  KOB: `Kobil Systems GmbH`,
  KOD: `Eastman Kodak Company`,
  KOE: `Kolter Electronic`,
  KOL: `Kollmorgen Motion Technologies Group`,
  KOM: `Kontron GmbH`,
  KOP: `Kopin Corporation`,
  KOU: `Kouziro`,
  KOW: `KOWA Company`,
  KPC: `King Phoenix Company`,
  KPT: `TPK Holding`,
  KRL: `Krell Industries`,
  KRM: `Kroma Telecom`,
  KRY: `Kroy`,
  KSC: `Kinetic Systems Corporation`,
  KSG: `KUPA China Shenzhen Micro Technology Co., Ltd. Gold Institute`,
  KSL: `Karn Solutions`,
  KSX: `King Tester Corporation`,
  KTC: `Kingston Tech Corporation`,
  KTD: `Takahata Electronics`,
  KTE: `K-Tech`,
  KTG: `Kayser-Threde GmbH`,
  KTI: `Konica Technical`,
  KTK: `Key Tronic Corporation`,
  KTN: `Katron Tech`,
  KTS: `Kyokko Communication System`,
  KUR: `Kurta Corporation`,
  KVA: `Kvaser AB`,
  KVX: `KeyView`,
  KWD: `Kenwood Corporation`,
  KYC: `Kyocera Corporation`,
  KYE: `KYE Syst Corporation`,
  KYK: `Samsung Electronics America`,
  KYN: `KEYENCE CORPORATION`,
  KZI: `K-Zone International`,
  KZN: `K-Zone International`,
  LAB: `ACT Labs`,
  LAC: `LaCie`,
  LAF: `Microline`,
  LAG: `Laguna Systems`,
  LAN: `Sodeman Lancom`,
  LAS: `LASAT Comm. A/S`,
  LAV: `Lava Computer MFG`,
  LBC: `LABAU Technology Corp.`,
  LBO: `Lubosoft`,
  LCC: `LCI`,
  LCD: `Toshiba Matsushita Display Technology`,
  LCE: `La Commande Electronique`,
  LCI: `Lite-On Communication`,
  LCM: `Latitude Comm.`,
  LCN: `LEXICON`,
  LCP: `Silent Power Electronics GmbH`,
  LCS: `Longshine Electronics Company`,
  LCT: `Labcal Technologies`,
  LDN: `Laserdyne Technologies`,
  LDT: `LogiDataTech Electronic GmbH`,
  LEC: `Lectron Company`,
  LED: `Long Engineering Design`,
  LEG: `Legerity`,
  LEN: `Lenovo Group`,
  LEO: `First International Computer`,
  LEX: `Lexical`,
  LGC: `Logic`,
  LGD: `LG Display`,
  LGI: `Logitech`,
  LGS: `LG Semicom Company`,
  LGX: `Lasergraphics`,
  LHA: `Lars Haagh ApS`,
  LHC: `Beihai Century Joint Innovation Technology`,
  LHE: `Lung Hwa Electronics Company`,
  LHT: `Lighthouse Technologies`,
  LIN: `Lenovo Beijing`,
  LIP: `Linked IP GmbH`,
  LIS: `Life is Style`,
  LIT: `Lithics Silicon Technology`,
  LJX: `Datalogic Corporation`,
  LKM: `Likom Technology Sdn. Bhd.`,
  LLL: `L-3 Communications`,
  LLT: `LUMINO Licht Elektronik GmbH`,
  LMG: `Lucent Technologies`,
  LMI: `Lexmark Int'l`,
  LMP: `Leda Media Products`,
  LMS: `Lumens Digital Optics`,
  LMT: `Laser Master`,
  LNC: `Lincoln Technology Solutions`,
  LND: `Land Computer Company`,
  LNK: `Link Tech`,
  LNR: `Linear Systems`,
  LNT: `LANETCO International`,
  LNV: `Lenovo`,
  LNX: `The Linux Foundation`,
  LOC: `Locamation B.V.`,
  LOE: `Loewe Opta GmbH`,
  LOG: `Logicode Technology`,
  LOL: `Litelogic Operations`,
  LPE: `El-PUSK`,
  LPI: `Design Technology`,
  LPL: `LG Philips`,
  LSC: `LifeSize Communications`,
  LSD: `Intersil Corporation`,
  LSI: `Loughborough Sound Images`,
  LSJ: `LSI Japan Company`,
  LSL: `Logical Solutions`,
  LSP: `Lightspace Technologies`,
  LSY: `LSI Systems`,
  LTC: `Labtec`,
  LTI: `Jongshine Tech`,
  LTK: `Lucidity Technology Company`,
  LTN: `Lite-On`,
  LTS: `LTS Scale`,
  LTV: `Leitch Technology International`,
  LTW: `Lightware`,
  LUC: `Lucent Technologies`,
  LUM: `Lumagen`,
  LUX: `Luxxell Research`,
  LVI: `LVI Low Vision International AB`,
  LWC: `Labway Corporation`,
  LWR: `Lightware Visual Engineering`,
  LWW: `Lanier Worldwide`,
  LXC: `LXCO Technologies AG`,
  LXN: `Luxeon`,
  LXS: `ELEA CardWare`,
  LZX: `Lightwell Company`,
  MAC: `MAC System Company`,
  MAD: `Xedia Corporation`,
  MAE: `Maestro`,
  MAG: `MAG InnoVision`,
  MAI: `Mutoh America`,
  MAL: `Meridian Audio`,
  MAN: `LGIC`,
  MAS: `Mass`,
  MAT: `Panasonic Connect`,
  MAX: `Rogen Tech Distribution`,
  MAY: `Maynard Electronics`,
  MAZ: `MAZeT GmbH`,
  MBC: `MBC`,
  MBD: `Microbus PLC`,
  MBM: `Marshall Electronics`,
  MBV: `Moreton Bay`,
  MCA: `American Nuclear Systems`,
  MCC: `Micro Industries`,
  MCD: `McDATA Corporation`,
  MCE: `Metz-Werke GmbH & Co KG`,
  MCG: `Motorola Computer Group`,
  MCI: `Micronics Computers`,
  MCJ: `Medicaroid Corporation`,
  MCL: `Motorola Communications Israel`,
  MCM: `Metricom`,
  MCN: `Micron Electronics`,
  MCO: `Motion Computing`,
  MCP: `Magni Systems`,
  MCQ: `Mat's Computers`,
  MCR: `Marina Communicaitons`,
  MCS: `Micro Computer Systems`,
  MCT: `Microtec`,
  MCX: `Millson Custom Solutions`,
  MDA: `Media4`,
  MDC: `Midori Electronics`,
  MDD: `MODIS`,
  MDF: `MILDEF AB`,
  MDG: `Madge Networks`,
  MDI: `Micro Design`,
  MDK: `Mediatek Corporation`,
  MDO: `Panasonic`,
  MDR: `Medar`,
  MDS: `Micro Display Systems`,
  MDT: `Magus Data Tech`,
  MDV: `MET Development`,
  MDX: `MicroDatec GmbH`,
  MDY: `Microdyne`,
  MEC: `Mega System Technologies`,
  MED: `Messeltronik Dresden GmbH`,
  MEE: `Mitsubishi Electric Engineering`,
  MEG: `Abeam Tech`,
  MEI: `Panasonic Industry Company`,
  MEJ: `Mac-Eight`,
  MEK: `Mediaedge Corporation`,
  MEL: `Mitsubishi Electric Corporation`,
  MEN: `MEN Mikroelectronik Nueruberg GmbH`,
  MEP: `Meld Technology`,
  MEQ: `Matelect`,
  MET: `Metheus Corporation`,
  MEU: `MPL AG, Elektronik-Unternehmen`,
  MEX: `MSC Vertriebs GmbH`,
  MFG: `MicroField Graphics`,
  MFI: `Micro Firmware`,
  MFR: `MediaFire Corp.`,
  MGA: `Mega System Technologies`,
  MGC: `Mentor Graphics Corporation`,
  MGE: `Schneider Electric S.A.`,
  MGL: `M-G Technology`,
  MGT: `Megatech R & D Company`,
  MHQ: `Moxa`,
  MIC: `Micom Communications`,
  MID: `Miro Displays`,
  MII: `Mitec`,
  MIL: `Marconi Instruments`,
  MIM: `Mimio - A Newell Rubbermaid Company`,
  MIN: `Minicom Digital Signage`,
  MIP: `MicronPC.com`,
  MIR: `Miro Computer Prod.`,
  MIS: `Modular Industrial Solutions`,
  MIT: `MCM Industrial Technology GmbH`,
  MIV: `MicroImage Video Systems`,
  MJI: `Marantz Japan`,
  MJS: `MJS Designs`,
  MKC: `Media Tek`,
  MKS: `MK Seiko`,
  MKT: `Microtek`,
  MKV: `Trtheim Technology`,
  MLC: `Milcots`,
  MLD: `Deep Video Imaging`,
  MLG: `Micrologica AG`,
  MLI: `McIntosh Laboratory`,
  MLL: `Millogic`,
  MLM: `Millennium Engineering`,
  MLN: `Mark Levinson`,
  MLP: `Magic Leap`,
  MLS: `Milestone EPE`,
  MLT: `Wanlida Group`,
  MLX: `Mylex Corporation`,
  MMA: `Micromedia AG`,
  MMD: `Micromed Biotecnologia`,
  MMF: `Minnesota Mining and Manufacturing`,
  MMI: `Multimax`,
  MMM: `Electronic Measurements`,
  MMN: `MiniMan`,
  MMS: `MMS Electronics`,
  MMT: `MIMO Monitors`,
  MNC: `Mini Micro Methods`,
  MNI: `Marseille`,
  MNL: `Monorail`,
  MNP: `Microcom`,
  MNS: `Maxnerva Technology Services`,
  MOC: `Matrix Orbital Corporation`,
  MOD: `Modular Technology`,
  MOK: `Moka International`,
  MOM: `Momentum Data Systems`,
  MOS: `Moses Corporation`,
  MOT: `Motorola UDS`,
  MPC: `M-Pact`,
  MPI: `Mediatrix Peripherals`,
  MPJ: `Microlab`,
  MPL: `Maple Research Inst. Company`,
  MPN: `Mainpine`,
  MPS: `MPS Software GmbH`,
  MPV: `Megapixel Visual Realty`,
  MPX: `Micropix Technologies`,
  MQP: `MultiQ Products AB`,
  MRA: `Miranda Technologies`,
  MRC: `Marconi Simulation & Ty-Coch Way Training`,
  MRD: `MicroDisplay Corporation`,
  MRG: `Nreal`,
  MRK: `Maruko & Company`,
  MRL: `Miratel`,
  MRO: `Medikro Oy`,
  MRT: `Merging Technologies`,
  MSA: `Micro Systemation AB`,
  MSC: `Mouse Systems Corporation`,
  MSD: `Datenerfassungs- und Informationssysteme`,
  MSF: `M-Systems Flash Disk Pioneers`,
  MSG: `MSI GmbH`,
  MSH: `Microsoft`,
  MSI: `Microstep`,
  MSK: `Megasoft`,
  MSL: `MicroSlate`,
  MSM: `Advanced Digital Systems`,
  MSP: `Mistral Solutions [P]`,
  MSR: `MASPRO DENKOH Corp.`,
  MST: `MS Telematica`,
  MSU: `motorola`,
  MSV: `Mosgi Corporation`,
  MSX: `Micomsoft`,
  MSY: `MicroTouch Systems`,
  MTA: `Meta Watch`,
  MTB: `Media Technologies`,
  MTC: `Mars-Tech Corporation`,
  MTD: `MindTech Display`,
  MTE: `MediaTec GmbH`,
  MTH: `Micro-Tech Hearing Instruments`,
  MTI: `MaxCom Technical`,
  MTJ: `MicroTechnica`,
  MTK: `Microtek International`,
  MTL: `Mitel Corporation`,
  MTM: `Motium`,
  MTN: `Mtron Storage Technology`,
  MTR: `Mitron computer`,
  MTS: `Multi-Tech Systems`,
  MTT: `Moore Threads Virtual Display`,
  MTU: `Mark of the Unicorn`,
  MTX: `Matrox`,
  MUD: `Multi-Dimension Institute`,
  MUK: `Mainpine`,
  MVD: `Microvitec PLC`,
  MVI: `Media Vision`,
  MVM: `SOBO VISION`,
  MVN: `Meta Company`,
  MVR: `MediCapture`,
  MVS: `Microvision`,
  MVX: `COM 1`,
  MWI: `Multiwave Innovation Pte`,
  MWR: `mware`,
  MWY: `Microway`,
  MXD: `MaxData Computer GmbH & Co.KG`,
  MXI: `Macronix`,
  MXL: `Hitachi Maxell`,
  MXM: `C&T Solution`,
  MXP: `Maxpeed Corporation`,
  MXT: `Maxtech Corporation`,
  MXV: `MaxVision Corporation`,
  MYA: `Monydata`,
  MYR: `Myriad Solutions`,
  MYX: `Micronyx`,
  NAC: `Ncast Corporation`,
  NAD: `NAD Electronics`,
  NAF: `NAFASAE INDIA Pvt.`,
  NAK: `Nakano Engineering`,
  NAL: `Network Alchemy`,
  NAT: `NaturalPoint`,
  NAV: `Navigation Corporation`,
  NAX: `Naxos Tecnologia`,
  NBL: `N*Able Technologies`,
  NBS: `National Key Lab. on ISN`,
  NBT: `NingBo Bestwinning Technology`,
  NCA: `Nixdorf Company`,
  NCC: `NCR Corporation`,
  NCE: `Norcent Technology`,
  NCI: `NewCom`,
  NCL: `NetComm`,
  NCP: `Najing CEC Panda FPD Technology`,
  NCR: `NCR Electronics`,
  NCS: `Northgate Computer Systems`,
  NCT: `NEC CustomTechnica`,
  NCV: `NewCoSemi (Beijing) Technology`,
  NDC: `National DataComm Corporaiton`,
  NDF: `NDF Special Light Products B.V.`,
  NDI: `National Display Systems`,
  NDK: `Naitoh Densei`,
  NDL: `Network Designers`,
  NDS: `Nokia Data`,
  NEC: `NEC Corporation`,
  NEO: `NEO TELECOM`,
  NES: `INNES`,
  NET: `Mettler Toledo`,
  NEU: `NEUROTEC - EMPRESA DE PESQUISA E DESENVOLVIMENTO EM BIOMEDICINA`,
  NEX: `Nexgen Mediatech`,
  NFC: `BTC Korea`,
  NFS: `Number Five Software`,
  NGC: `Network General`,
  NGS: `A D S Exports`,
  NHC: `New H3C Technology`,
  NHT: `Vinci Labs`,
  NIC: `National Instruments Corporation`,
  NIS: `Nissei Electric Company`,
  NIT: `Network Info Technology`,
  NIX: `Seanix Technology`,
  NLC: `Next Level Communications`,
  NME: `Navico`,
  NMP: `Nokia Mobile Phones`,
  NMS: `Natural Micro System`,
  NMV: `NEC-Mitsubishi Electric Visual Systems Corporation`,
  NMX: `Neomagic`,
  NNC: `NNC`,
  NOD: `3NOD Digital Technology`,
  NOE: `NordicEye AB`,
  NOI: `North Invent A/S`,
  NOK: `Nokia Display Products`,
  NOR: `Norand Corporation`,
  NOT: `Not`,
  NPA: `Arvanics`,
  NPI: `Network Peripherals`,
  NRI: `Noritake Itron Corporation`,
  NRL: `U.S. Naval Research Lab`,
  NRT: `Beijing Northern Radiantelecom`,
  NRV: `Taugagreining hf`,
  NSA: `NeuroSky`,
  NSC: `National Semiconductor Corporation`,
  NSI: `NISSEI ELECTRIC`,
  NSP: `Nspire System`,
  NSS: `Newport Systems Solutions`,
  NST: `Network Security Technology Co`,
  NTC: `NeoTech S.r.l`,
  NTI: `New Tech Int'l Company`,
  NTK: `NewTek`,
  NTL: `National Transcomm.`,
  NTN: `Nuvoton Technology Corporation`,
  NTR: `N-trig Innovative Technologies`,
  NTS: `Nits Technology`,
  NTT: `NTT Advanced Technology Corporation`,
  NTW: `Networth`,
  NTX: `Netaccess`,
  NUG: `NU Technology`,
  NUI: `NU`,
  NVC: `NetVision Corporation`,
  NVD: `Nvidia`,
  NVI: `NuVision US`,
  NVL: `Novell`,
  NVO: `Netvio`,
  NVR: `NOLO`,
  NVT: `Navatek Engineering Corporation`,
  NWC: `NW Computer Engineering`,
  NWL: `Newline Interactive`,
  NWP: `NovaWeb Technologies`,
  NWS: `Newisys`,
  NXC: `NextCom K.K.`,
  NXE: `Norxe AS`,
  NXG: `Nexgen`,
  NXP: `NXP Semiconductors bv.`,
  NXQ: `Nexiq Technologies`,
  NXR: `Nextorage Corporation`,
  NXS: `Technology Nexus Secure Open Systems AB`,
  NXT: `NZXT (PNP same EDID)_`,
  NYC: `Nakayo Relecommunications`,
  OAK: `Oak Tech`,
  OAS: `Oasys Technology Company`,
  OBS: `Optibase Technologies`,
  OCD: `Macraigor Systems`,
  OCN: `Olfan`,
  OCS: `Open Connect Solutions`,
  ODM: `ODME`,
  ODR: `Odrac`,
  OEC: `ORION ELECTRIC`,
  OEI: `Optum Engineering`,
  OFI: `Jiangxi Jinghao Optical`,
  OHW: `M-Labs`,
  OIC: `Option Industrial Computers`,
  OIM: `Option International`,
  OIN: `Option International`,
  OKI: `OKI Electric Industrial Company`,
  OLC: `Olicom A/S`,
  OLD: `Olidata S.p.A.`,
  OLI: `Olivetti`,
  OLT: `Olitec S.A.`,
  OLV: `Olitec S.A.`,
  OLY: `OLYMPUS CORPORATION`,
  OMC: `OBJIX Multimedia Corporation`,
  OMG: `RODE`,
  OMN: `Omnitel`,
  OMR: `Omron Corporation`,
  ONE: `Oneac Corporation`,
  ONK: `ONKYO Corporation`,
  ONL: `OnLive`,
  ONS: `On Systems`,
  ONW: `OPEN Networks`,
  ONX: `SOMELEC Z.I. Du Vert Galanta`,
  OOS: `OSRAM`,
  OPC: `Opcode`,
  OPI: `D.N.S. Corporation`,
  OPP: `OPPO Digital`,
  OPT: `OPTi`,
  OPV: `Optivision`,
  OQI: `OptiQuest`,
  ORG: `ORGA Kartensysteme GmbH`,
  ORI: `OSR Open Systems Resources`,
  ORN: `ORION ELECTRIC`,
  OSA: `OSAKA Micro Computer`,
  OSD: `Optical Systems Design`,
  OSI: `Open Stack`,
  OSP: `OPTI-UPS Corporation`,
  OSR: `Oksori Company`,
  OTB: `outsidetheboxstuff.com`,
  OTI: `Orchid Technology`,
  OTK: `OmniTek`,
  OTM: `Optoma Corporation`,
  OTT: `OPTO22`,
  OUK: `OUK Company`,
  OVR: `Oculus VR`,
  OWL: `Mediacom Technologies Pte`,
  OXU: `Oxus Research S.A.`,
  OYO: `Shadow Systems`,
  OZC: `OZ Corporation`,
  OZD: `OZO Co.`,
  OZO: `Tribe Computer Works`,
  PAC: `Pacific Avionics Corporation`,
  PAD: `Promotion and Display Technology`,
  PAE: `PreSonus Audio Electronics`,
  PAK: `Many CNC System`,
  PAM: `Peter Antesberger Messtechnik`,
  PAN: `The Panda Project`,
  PAR: `Parallan Comp`,
  PBI: `Pitney Bowes`,
  PBL: `Packard Bell Electronics`,
  PBN: `Packard Bell NEC`,
  PBV: `Pitney Bowes`,
  PCA: `Philips BU Add On Card`,
  PCB: `OCTAL S.A.`,
  PCC: `PowerCom Technology Company`,
  PCG: `First Industrial Computer`,
  PCI: `Pioneer Computer`,
  PCK: `PCBANK21`,
  PCL: `pentel.co.`,
  PCM: `PCM Systems Corporation`,
  PCO: `Performance Concepts`,
  PCP: `Procomp USA`,
  PCS: `Toshiba Personal Computer System Corporation`,
  PCT: `PC-Tel`,
  PCW: `Pacific CommWare`,
  PCX: `PC Xperten`,
  PDM: `Psion Dacom Plc.`,
  PDN: `AT&T Paradyne`,
  PDR: `Pure Data`,
  PDS: `PD Systems International`,
  PDT: `PDTS - Prozessdatentechnik und Systeme`,
  PDV: `Prodrive B.V.`,
  PEC: `POTRANS Electrical Corp.`,
  PEG: `Pegatron Corporation`,
  PEI: `PEI Electronics`,
  PEL: `Primax Electric`,
  PEN: `Interactive Computer Products`,
  PEP: `Peppercon AG`,
  PER: `Perceptive Signal Technologies`,
  PET: `Practical Electronic Tools`,
  PFT: `Telia ProSoft AB`,
  PGI: `PACSGEAR`,
  PGM: `Paradigm Advanced Research Centre`,
  PGP: `propagamma kommunikation`,
  PGS: `Princeton Graphic Systems`,
  PHC: `Pijnenburg Beheer N.V.`,
  PHE: `Philips Medical Systems Boeblingen GmbH`,
  PHI: `DO NOT USE - PHI`,
  PHL: `Philips Consumer Electronics Company`,
  PHO: `Photonics Systems`,
  PHS: `Philips Communication Systems`,
  PHY: `Phylon Communications`,
  PIC: `Picturall`,
  PIE: `Pacific Image Electronics Company`,
  PIM: `Prism`,
  PIO: `Pioneer Electronic Corporation`,
  PIR: `Pico Technology`,
  PIS: `TECNART`,
  PIX: `Pixie Tech`,
  PJA: `Projecta`,
  PJD: `Projectiondesign AS`,
  PJT: `Pan Jit International`,
  PKA: `Acco UK`,
  PLC: `Pro-Log Corporation`,
  PLF: `Panasonic Avionics Corporation`,
  PLM: `PROLINK Microsystems Corp.`,
  PLT: `PT Hartono Istana Teknologi`,
  PLV: `PLUS Vision Corp.`,
  PLX: `Parallax Graphics`,
  PLY: `Polycom`,
  PMC: `PMC Consumer Electronics`,
  PMD: `TDK USA Corporation`,
  PMM: `Point Multimedia System`,
  PMS: `Pabian Embedded Systems`,
  PMT: `Promate Electronic`,
  PMX: `Photomatrix`,
  PNG: `Microsoft`,
  PNL: `Panelview`,
  PNP: `Microsoft`,
  PNR: `Planar Systems`,
  PNS: `PanaScope`,
  PNT: `HOYA Corporation PENTAX Lifecare Division`,
  PNX: `Phoenix Technologies`,
  POL: `PolyComp (PTY)`,
  PON: `Perpetual Technologies`,
  POR: `Portalis LC`,
  POS: `Positivo Tecnologia S.A.`,
  POT: `Parrot`,
  PPC: `Phoenixtec Power Company`,
  PPD: `MEPhI`,
  PPI: `Practical Peripherals`,
  PPM: `Clinton Electronics Corp.`,
  PPP: `Purup Prepress AS`,
  PPR: `PicPro`,
  PPX: `Perceptive Pixel`,
  PQI: `Pixel Qi`,
  PRA: `PRO/AUTOMATION`,
  PRC: `PerComm`,
  PRD: `Praim S.r.l.`,
  PRF: `Schneider Electric Japan Holdings`,
  PRG: `The Phoenix Research Group`,
  PRI: `Priva Hortimation BV`,
  PRM: `Prometheus`,
  PRO: `Proteon`,
  PRP: `UEFI Forum`,
  PRS: `Leutron Vision`,
  PRT: `Parade Technologies`,
  PRX: `Proxima Corporation`,
  PSA: `Advanced Signal Processing Technologies`,
  PSC: `Philips Semiconductors`,
  PSD: `Peus-Systems GmbH`,
  PSE: `Practical Solutions Pte.`,
  PSI: `PSI-Perceptive Solutions`,
  PSL: `Perle Systems`,
  PSM: `Prosum`,
  PST: `Global Data SA`,
  PSY: `Prodea Systems`,
  PTA: `PAR Tech`,
  PTC: `PS Technology Corporation`,
  PTG: `Cipher Systems`,
  PTH: `Pathlight Technology`,
  PTI: `Promise Technology`,
  PTL: `Pantel`,
  PTS: `Plain Tree Systems`,
  PTW: `DO NOT USE - PTW`,
  PTX: `Printronix`,
  PUL: `Pulse-Eight`,
  PVC: `DO NOT USE - PVC`,
  PVG: `Proview Global`,
  PVI: `Prime View International`,
  PVM: `Penta Studiotechnik GmbH`,
  PVN: `Pixel Vision`,
  PVP: `Klos Technologies`,
  PVR: `Pimax Tech.`,
  PXC: `Phoenix Contact`,
  PXE: `Pixela Corporation`,
  PXL: `The Moving Pixel Company`,
  PXM: `Proxim`,
  PXN: `PixelNext`,
  PXO: `Pixio USA`,
  QCC: `QuakeCom Company`,
  QCH: `Metronics`,
  QCI: `Quanta Computer`,
  QCK: `Quick Corporation`,
  QCL: `Quadrant Components`,
  QCP: `Qualcomm`,
  QDI: `Quantum Data Incorporated`,
  QDL: `QD Laser`,
  QDM: `Quadram`,
  QDS: `Quanta Display`,
  QFF: `Padix`,
  QFI: `Quickflex`,
  QLC: `Q-Logic`,
  QQQ: `Chuomusen`,
  QSC: `QSC`,
  QSI: `Quantum Solutions`,
  QTD: `Quantum 3D`,
  QTH: `Questech`,
  QTI: `Quicknet Technologies`,
  QTM: `Quantum`,
  QTR: `Qtronix Corporation`,
  QUA: `Quatographic AG`,
  QUE: `Questra Consulting`,
  QVU: `Quartics`,
  RAC: `Racore Computer Products`,
  RAD: `Radisys Corporation`,
  RAI: `Rockwell Automation/Intecolor`,
  RAN: `Rancho Tech`,
  RAR: `Raritan`,
  RAS: `RAScom`,
  RAT: `Rent-A-Tech`,
  RAY: `Raylar Design`,
  RCE: `Parc d'Activite des Bellevues`,
  RCH: `Reach Technology`,
  RCI: `RC International`,
  RCN: `Radio Consult S.r.l.`,
  RCO: `Rockwell Collins`,
  RDI: `Rainbow Displays`,
  RDL: `Riedel Communications Canada`,
  RDM: `Tremon Enterprises Company`,
  RDN: `RADIODATA GmbH`,
  RDS: `Radius`,
  REA: `Real D`,
  REC: `ReCom`,
  RED: `Research Electronics Development`,
  REF: `Reflectivity`,
  REH: `Rehan Electronics`,
  REL: `Reliance Electric Ind Corporation`,
  REM: `SCI Systems`,
  REN: `Renesas Technology Corp.`,
  RES: `ResMed`,
  RET: `Resonance Technology`,
  REV: `Revolution Display`,
  REX: `RATOC Systems`,
  RFI: `RAFI GmbH & Co. KG`,
  RFX: `Redfox Technologies`,
  RGB: `RGB Spectrum`,
  RGL: `Robertson Geologging`,
  RHD: `RightHand Technologies`,
  RHM: `Rohm Company`,
  RHT: `Red Hat`,
  RIC: `RICOH COMPANY`,
  RII: `Racal Interlan`,
  RIO: `Rios Systems Company`,
  RIT: `Ritech`,
  RIV: `Rivulet Communications`,
  RJA: `Roland Corporation`,
  RJS: `Advanced Engineering`,
  RKC: `Reakin Technolohy Corporation`,
  RLD: `MEPCO`,
  RLN: `RadioLAN`,
  RMC: `Raritan Computer`,
  RMP: `Research Machines`,
  RMS: `Shenzhen Ramos Digital Technology`,
  RMT: `Roper Mobile`,
  RNB: `Rainbow Technologies`,
  RNL: `Reonel Oy`,
  ROB: `Robust Electronics GmbH`,
  ROH: `Rohm`,
  ROK: `Rockwell International`,
  ROP: `Roper International`,
  ROS: `Rohde & Schwarz`,
  RPI: `RoomPro Technologies`,
  RPL: `Raspberry Pi`,
  RPT: `R.P.T.Intergroups`,
  RRI: `Radicom Research`,
  RRO: `AVARRO`,
  RSC: `PhotoTelesis`,
  RSH: `ADC-Centre`,
  RSI: `Rampage Systems`,
  RSN: `Radiospire Networks`,
  RSQ: `R Squared`,
  RSR: `Zhong Shan City Richsound Electronic Industrial`,
  RSS: `Rockwell Semiconductor Systems`,
  RSV: `Ross Video`,
  RSX: `Rapid Tech Corporation`,
  RTC: `Relia Technologies`,
  RTI: `Rancho Tech`,
  RTK: `DO NOT USE - RTK`,
  RTL: `Realtek Semiconductor Company`,
  RTS: `Raintree Systems`,
  RUN: `RUNCO International`,
  RUP: `Ups Manufactoring S.r.l.`,
  RVC: `RSI Systems`,
  RVI: `Realvision`,
  RVL: `Reveal Computer Prod`,
  RWC: `Red Wing Corporation`,
  RXT: `Tectona SoftSolutions (P)`,
  RZR: `Razer Taiwan`,
  RZS: `Rozsnyó, s.r.o.`,
  SAA: `Sanritz Automation`,
  SAE: `Saab Aerotech`,
  SAG: `Sedlbauer`,
  SAI: `Sage`,
  SAK: `Saitek`,
  SAM: `Samsung Electric Company`,
  SAN: `Sanyo Electric`,
  SAS: `Stores Automated Systems`,
  SAT: `Shuttle Tech`,
  SBC: `Shanghai Bell Telephone Equip Mfg Co`,
  SBD: `Softbed - Consulting & Development`,
  SBI: `SMART Technologies`,
  SBS: `SBS-or Industrial Computers GmbH`,
  SBT: `Senseboard Technologies AB`,
  SCA: `Schneider Consumer Group`,
  SCB: `SeeCubic B.V.`,
  SCC: `SORD Computer Corporation`,
  SCD: `Sanyo Electric Company`,
  SCE: `Sun Corporation`,
  SCG: `Seco S.p.A.`,
  SCH: `Schlumberger Cards`,
  SCI: `System Craft`,
  SCL: `Sigmacom`,
  SCM: `SCM Microsystems`,
  SCN: `Scanport`,
  SCO: `SORCUS Computer GmbH`,
  SCP: `Scriptel Corporation`,
  SCR: `Systran Corporation`,
  SCS: `Nanomach Anstalt`,
  SCT: `Smart Card Technology`,
  SCX: `Socionext`,
  SDA: `SAT (Societe Anonyme)`,
  SDC: `Samsung Display Corp.`,
  SDD: `Intrada-SDD`,
  SDE: `Sherwood Digital Electronics Corporation`,
  SDF: `SODIFF E&T`,
  SDH: `Communications Specialies`,
  SDI: `Samtron Displays`,
  SDK: `SAIT-Devlonics`,
  SDR: `SDR Systems`,
  SDS: `SunRiver Data System`,
  SDT: `Siemens AG`,
  SDX: `SDX Business Systems`,
  SEA: `Seanix Technology`,
  SEB: `System Elektronik GmbH`,
  SEC: `Seiko Epson Corporation`,
  SEE: `SeeColor Corporation`,
  SEG: `DO NOT USE - SEG`,
  SEI: `Seitz & Associates`,
  SEL: `Way2Call Communications`,
  SEM: `Samsung Electronics Company`,
  SEN: `Sencore`,
  SEO: `SEOS`,
  SEP: `SEP Eletronica Ltda.`,
  SER: `Sony Ericsson Mobile Communications`,
  SES: `Session Control`,
  SET: `SendTek Corporation`,
  SFL: `Shiftall`,
  SFM: `TORNADO Company`,
  SFT: `Mikroforum Ring 3`,
  SGC: `Spectragraphics Corporation`,
  SGD: `Sigma Designs`,
  SGE: `Kansai Electric Company`,
  SGI: `Scan Group`,
  SGL: `Super Gate Technology Company`,
  SGM: `SAGEM`,
  SGN: `Shenzhen Soogeen Electronics`,
  SGO: `Logos Design A/S`,
  SGT: `Stargate Technology`,
  SGW: `Shanghai Guowei Science and Technology`,
  SGX: `Silicon Graphics`,
  SGZ: `Systec Computer GmbH`,
  SHC: `ShibaSoku`,
  SHG: `Soft & Hardware development Goldammer GmbH`,
  SHI: `Jiangsu Shinco Electronic Group`,
  SHP: `Sharp Corporation`,
  SHR: `Digital Discovery`,
  SHT: `Shin Ho Tech`,
  SHU: `Shure`,
  SIA: `SIEMENS AG`,
  SIB: `Sanyo Electric Company`,
  SIC: `Sysmate Corporation`,
  SID: `Seiko Instruments Information Devices`,
  SIE: `Siemens`,
  SIG: `Sigma Designs`,
  SII: `Silicon Image`,
  SIL: `Silicon Laboratories`,
  SIM: `S3`,
  SIN: `Singular Technology`,
  SIR: `Sirius Technologies`,
  SIS: `Silicon Integrated Systems Corporation`,
  SIT: `Sitintel`,
  SIU: `Seiko Instruments USA`,
  SIX: `Zuniq Data Corporation`,
  SJE: `Sejin Electron`,
  SKD: `Schneider & Koch`,
  SKG: `Shenzhen KTC Technology Group`,
  SKI: `SKTB "SKiT"`,
  SKM: `Guangzhou Teclast Information Technology`,
  SKT: `Samsung Electro-Mechanics Company`,
  SKW: `Skyworth`,
  SKY: `SKYDATA S.P.A.`,
  SLA: `Systeme Lauer GmbH&Co KG`,
  SLB: `Shlumberger`,
  SLC: `Syslogic Datentechnik AG`,
  SLF: `StarLeaf`,
  SLH: `Silicon Library`,
  SLI: `Symbios Logic`,
  SLK: `Silitek Corporation`,
  SLM: `Solomon Technology Corporation`,
  SLR: `Schlumberger Technology Corporate`,
  SLS: `Schnick-Schnack-Systems GmbH`,
  SLT: `Salt Internatioinal Corp.`,
  SLX: `Specialix`,
  SMA: `SMART Modular Technologies`,
  SMB: `Schlumberger`,
  SMC: `Standard Microsystems Corporation`,
  SME: `Sysmate Company`,
  SMI: `SpaceLabs Medical`,
  SMK: `SMK Corporation`,
  SML: `Sumitomo Metal Industries`,
  SMM: `Shark Multimedia`,
  SMN: `Somnium Space`,
  SMO: `STMicroelectronics`,
  SMP: `Simple Computing`,
  SMR: `B.& V. S.r.l.`,
  SMS: `Silicom Multimedia Systems`,
  SMT: `Silcom Manufacturing Tech`,
  SNC: `Sentronic International Corp.`,
  SNI: `Siemens Microdesign GmbH`,
  SNK: `S&K Electronics`,
  SNN: `Sunny Elektronik`,
  SNO: `Sinosun Technology`,
  SNP: `Siemens Nixdorf Info Systems`,
  SNS: `Cirtech (UK)`,
  SNT: `SuperNet`,
  SNV: `Sonove GmbH`,
  SNW: `Snell & Wilcox`,
  SNX: `Sonix Comm.`,
  SNY: `Sony`,
  SOC: `Santec Corporation`,
  SOI: `Silicon Optix Corporation`,
  SOL: `Solitron Technologies`,
  SON: `Sony`,
  SOR: `Sorcus Computer GmbH`,
  SOT: `Sotec Company`,
  SOY: `SOYO Group`,
  SPC: `SpinCore Technologies`,
  SPE: `SPEA Software AG`,
  SPH: `G&W Instruments GmbH`,
  SPI: `SPACE-I`,
  SPK: `SpeakerCraft`,
  SPL: `Smart Silicon Systems`,
  SPN: `Sapience Corporation`,
  SPO: `SAMPO CORPORATION`,
  SPR: `PMNS GmbH`,
  SPS: `Synopsys`,
  SPT: `Sceptre Tech`,
  SPU: `SIM2 Multimedia S.P.A.`,
  SPX: `Simplex Time Recorder`,
  SQT: `Sequent Computer Systems`,
  SRC: `Integrated Tech Express`,
  SRD: `Setred`,
  SRF: `Surf Communication Solutions`,
  SRG: `Intuitive Surgical`,
  SRS: `SR-Systems e.K.`,
  SRT: `SeeReal Technologies GmbH`,
  SSC: `Sierra Semiconductor`,
  SSD: `FlightSafety International`,
  SSE: `Samsung Electronic`,
  SSG: `Steelseries ApS`,
  SSI: `S-S Technology`,
  SSJ: `Sankyo Seiki Mfg.co.`,
  SSL: `Shenzhen South-Top Computer`,
  SSP: `Spectrum Signal Proecessing`,
  SSS: `S3`,
  SST: `SystemSoft Corporation`,
  STA: `ST Electronics Systems Assembly Pte`,
  STB: `STB Systems`,
  STC: `STAC Electronics`,
  STD: `STD Computer`,
  STE: `SII Ido-Tsushin`,
  STF: `Starflight Electronics`,
  STG: `StereoGraphics Corp.`,
  STH: `Semtech Corporation`,
  STI: `Smart Tech`,
  STK: `SANTAK CORP.`,
  STL: `SigmaTel`,
  STM: `SGS Thomson Microelectronics`,
  STN: `Samsung Electronics America`,
  STO: `Stollmann E+V GmbH`,
  STP: `StreamPlay`,
  STQ: `Synthetel Corporation`,
  STR: `Starlight Networks`,
  STS: `SITECSYSTEM`,
  STT: `Star Paging Telecom Tech (Shenzhen)`,
  STU: `Sentelic Corporation`,
  STV: `Beijing Guochengwantong Information Technology`,
  STW: `Starwin`,
  STX: `ST-Ericsson`,
  STY: `SDS Technologies`,
  SUB: `Subspace Comm.`,
  SUM: `Summagraphics Corporation`,
  SUN: `Sun Electronics Corporation`,
  SUP: `Supra Corporation`,
  SUR: `Surenam Computer Corporation`,
  SVA: `SGEG`,
  SVC: `Intellix Corp.`,
  SVD: `SVD Computer`,
  SVI: `Sun Microsystems`,
  SVR: `Sensics`,
  SVS: `SVSI`,
  SVT: `SEVIT`,
  SWC: `Software Café`,
  SWI: `Sierra Wireless`,
  SWL: `Sharedware`,
  SWO: `Guangzhou Shirui Electronics`,
  SWS: `Static`,
  SWT: `Software Technologies Group`,
  SXB: `Syntax-Brillian`,
  SXD: `Silex technology`,
  SXG: `SELEX GALILEO`,
  SXI: `Silex Inside`,
  SXL: `SolutionInside`,
  SXT: `Sharp Takaya Electronic Industry`,
  SYC: `Sysmic`,
  SYE: `SY Electronics`,
  SYK: `Stryker Communications`,
  SYL: `Sylvania Computer Products`,
  SYM: `Symicron Computer Communications`,
  SYN: `Synaptics`,
  SYP: `SYPRO Co`,
  SYS: `Sysgration`,
  SYT: `Seyeon Tech Company`,
  SYV: `SYVAX`,
  SYX: `Prime Systems`,
  SZM: `Shenzhen MTC`,
  TAA: `Tandberg`,
  TAB: `Todos Data System AB`,
  TAG: `Teles AG`,
  TAI: `Toshiba America Info Systems`,
  TAM: `Tamura Seisakusyo`,
  TAS: `Taskit Rechnertechnik GmbH`,
  TAT: `Teleliaison`,
  TAV: `Thales Avionics`,
  TAX: `Taxan (Europe)`,
  TBB: `Triple S Engineering`,
  TBC: `Turbo Communication`,
  TBS: `Turtle Beach System`,
  TCC: `Tandon Corporation`,
  TCD: `Taicom Data Systems`,
  TCE: `Century Corporation`,
  TCF: `Televic Conference`,
  TCH: `Interaction Systems`,
  TCI: `Tulip Computers Int'l B.V.`,
  TCJ: `TEAC America`,
  TCL: `Technical Concepts`,
  TCM: `3Com Corporation`,
  TCN: `Tecnetics (PTY)`,
  TCO: `Thomas-Conrad Corporation`,
  TCR: `Thomson Consumer Electronics`,
  TCS: `Tatung Company of America`,
  TCT: `Telecom Technology Centre`,
  TCX: `FREEMARS Heavy Industries`,
  TDC: `Teradici`,
  TDD: `Tandberg Data Display AS`,
  TDG: `Six15 Technologies`,
  TDM: `Tandem Computer Europe`,
  TDP: `3D Perception`,
  TDS: `Tri-Data Systems`,
  TDT: `TDT`,
  TDV: `TDVision Systems`,
  TDY: `Tandy Electronics`,
  TEA: `TEAC System Corporation`,
  TEC: `Tecmar`,
  TEK: `Tektronix`,
  TEL: `Promotion and Display Technology`,
  TEN: `Tencent`,
  TER: `TerraTec Electronic GmbH`,
  TET: `Tetradyne`,
  TEV: `Televés, S.A.`,
  TEZ: `Tech Source`,
  TGC: `Toshiba Global Commerce Solutions`,
  TGI: `TriGem Computer`,
  TGM: `TriGem Computer`,
  TGS: `Torus Systems`,
  TGV: `Grass Valley Germany GmbH`,
  TGW: `TechnoGym S.p.A.`,
  THN: `Thundercom Holdings Sdn. Bhd.`,
  TIC: `Trigem KinfoComm`,
  TIL: `Technical Illusions`,
  TIP: `TIPTEL AG`,
  TIV: `OOO Technoinvest`,
  TIX: `Tixi.Com GmbH`,
  TKC: `Taiko Electric Works`,
  TKG: `Tek Gear`,
  TKN: `Teknor Microsystem`,
  TKO: `TouchKo`,
  TKS: `TimeKeeping Systems`,
  TLA: `Ferrari Electronic GmbH`,
  TLD: `Telindus`,
  TLE: `Zhejiang Tianle Digital Electric`,
  TLF: `Teleforce Co`,
  TLI: `Toshiba Teli Corporation`,
  TLK: `Telelink AG`,
  TLL: `Thinklogical`,
  TLN: `Techlogix Networx`,
  TLS: `Teleste Educational OY`,
  TLT: `Dai Telecom S.p.A.`,
  TLV: `S3`,
  TLX: `Telxon Corporation`,
  TLY: `Truly Semiconductors`,
  TMA: `Tianma Microelectronics`,
  TMC: `Techmedia Computer Systems Corporation`,
  TME: `AT&T Microelectronics`,
  TMI: `Texas Microsystem`,
  TMM: `Time Management`,
  TMO: `Terumo Corporation`,
  TMR: `Taicom International`,
  TMS: `Trident Microsystems`,
  TMT: `T-Metrics`,
  TMV: `TeamViewer Germany GmbH`,
  TMX: `Thermotrex Corporation`,
  TNC: `TNC Industrial Company`,
  TNJ: `DO NOT USE - TNJ`,
  TNM: `Tecnimagen SA`,
  TNY: `Tennyson Tech`,
  TOE: `TOEI Electronics`,
  TOG: `The OPEN Group`,
  TOL: `TCL Corporation`,
  TOM: `Ceton Corporation`,
  TON: `TONNA`,
  TOP: `Orion Communications`,
  TOS: `Dynabook`,
  TOU: `Touchstone Technology`,
  TPC: `Touch Panel Systems Corporation`,
  TPD: `Times (Shanghai) Computer`,
  TPE: `Technology Power Enterprises`,
  TPJ: `Junnila`,
  TPK: `TOPRE CORPORATION`,
  TPR: `Topro Technology`,
  TPS: `Teleprocessing Systeme GmbH`,
  TPT: `Thruput`,
  TPV: `Top Victory Electronics (Fujian) Company`,
  TPZ: `Ypoaz Systems`,
  TRA: `TriTech Microelectronics International`,
  TRB: `Triumph Board a.s.`,
  TRC: `Trioc AB`,
  TRD: `Trident Microsystem`,
  TRE: `Tremetrics`,
  TRI: `Tricord Systems`,
  TRL: `Royal Information`,
  TRM: `Tekram Technology Company`,
  TRN: `Datacommunicatie Tron B.V.`,
  TRP: `Trapeze Group`,
  TRS: `Torus Systems`,
  TRT: `Tritec Electronic AG`,
  TRU: `Aashima Technology B.V.`,
  TRV: `Trivisio Prototyping GmbH`,
  TRX: `Trex Enterprises`,
  TSB: `Toshiba America Info Systems`,
  TSC: `Sanyo Electric Company`,
  TSD: `TechniSat Digital GmbH`,
  TSE: `Tottori Sanyo Electric`,
  TSF: `Racal-Airtech Software Forge`,
  TSG: `The Software Group`,
  TSH: `Elan Microelectronics Corporation`,
  TSI: `TeleVideo Systems`,
  TSL: `Tottori SANYO Electric`,
  TSP: `U.S. Navy`,
  TST: `Transtream`,
  TSV: `TRANSVIDEO`,
  TSW: `VRSHOW Technology`,
  TSY: `TouchSystems`,
  TTA: `Topson Technology`,
  TTB: `National Semiconductor Japan`,
  TTC: `Telecommunications Techniques Corporation`,
  TTE: `TTE`,
  TTI: `Trenton Terminals`,
  TTK: `Totoku Electric Company`,
  TTL: `2-Tel B.V`,
  TTP: `Toshiba Corporation`,
  TTR: `Hubei Century Joint Innovation Technology Co.`,
  TTS: `TechnoTrend Systemtechnik GmbH`,
  TTX: `Taitex Corporation`,
  TTY: `TRIDELITY Display Solutions GmbH`,
  TUA: `T+A elektroakustik GmbH`,
  TUT: `Tut Systems`,
  TVD: `Tecnovision`,
  TVI: `Truevision`,
  TVL: `Total Vision`,
  TVM: `Taiwan Video & Monitor Corporation`,
  TVO: `TV One`,
  TVR: `TV Interactive Corporation`,
  TVS: `TVS Electronics`,
  TVV: `TV1 GmbH`,
  TWA: `Tidewater Association`,
  TWE: `Kontron Electronik`,
  TWH: `Twinhead International Corporation`,
  TWI: `Easytel oy`,
  TWK: `TOWITOKO electronics GmbH`,
  TWX: `TEKWorx`,
  TXL: `Trixel`,
  TXN: `Texas Insturments`,
  TXT: `Textron Defense System`,
  TYN: `Tyan Computer Corporation`,
  UAS: `Ultima Associates Pte`,
  UBI: `Ungermann-Bass`,
  UBL: `Ubinetics`,
  UBU: `Canonical`,
  UDN: `Uniden Corporation`,
  UEC: `Ultima Electronics Corporation`,
  UEG: `Elitegroup Computer Systems Company`,
  UEI: `Universal Electronics`,
  UET: `Universal Empowering Technologies`,
  UFG: `UNIGRAF-USA`,
  UFO: `UFO Systems`,
  UGR: `Ugreen Group`,
  UHB: `XOCECO`,
  UIC: `Uniform Industrial Corporation`,
  UJR: `Ueda Japan Radio`,
  ULT: `Ultra Network Tech`,
  UMC: `United Microelectr Corporation`,
  UMG: `Umezawa Giken`,
  UMM: `Universal Multimedia`,
  UMT: `UltiMachine`,
  UNA: `Unisys DSD`,
  UNB: `Unisys Corporation`,
  UNC: `Unisys Corporation`,
  UND: `DO NOT USE - UND`,
  UNE: `DO NOT USE - UNE`,
  UNF: `DO NOT USE - UNF`,
  UNI: `Uniform Industry Corp.`,
  UNM: `Unisys Corporation`,
  UNO: `Unisys Corporation`,
  UNP: `Unitop`,
  UNS: `Unisys Corporation`,
  UNT: `Unisys Corporation`,
  UNY: `Unicate`,
  UPP: `UPPI`,
  UPS: `Systems Enhancement`,
  URD: `Video Computer S.p.A.`,
  USA: `Utimaco Safeware AG`,
  USD: `U.S. Digital Corporation`,
  USE: `U. S. Electronics`,
  USI: `Universal Scientific Industrial`,
  USR: `U.S. Robotics`,
  UTC: `Unicompute Technology`,
  UTD: `Up to Date Tech`,
  UWC: `Uniwill Computer Corp.`,
  VAD: `Vaddio`,
  VAI: `VAIO Corporation`,
  VAL: `Valence Computing Corporation`,
  VAR: `Varian Australia`,
  VAT: `VADATECH`,
  VAV: `aviica`,
  VBR: `VBrick Systems`,
  VBT: `Valley Board Ltda`,
  VCC: `Virtual Computer Corporation`,
  VCE: `VARCem`,
  VCI: `VistaCom`,
  VCJ: `Victor Company of Japan`,
  VCM: `Vector Magnetics`,
  VCX: `VCONEX`,
  VDA: `Victor Data Systems`,
  VDC: `VDC Display Systems`,
  VDM: `Vadem`,
  VDO: `Video & Display Oriented Corporation`,
  VDS: `Vidisys GmbH & Company`,
  VDT: `Viditec`,
  VEC: `Vector Informatik GmbH`,
  VEK: `Vektrex`,
  VES: `Vestel Elektronik Sanayi ve Ticaret A. S.`,
  VFI: `VeriFone`,
  VHI: `Macrocad Development`,
  VIA: `VIA Tech`,
  VIB: `Tatung UK`,
  VIC: `Victron B.V.`,
  VID: `Ingram Macrotron Germany`,
  VIK: `Viking Connectors`,
  VIM: `Via Mons`,
  VIN: `Vine Micros`,
  VIO: `Zake IP Holdings LLC (3B tech)`,
  VIR: `Visual Interface`,
  VIS: `Visioneer`,
  VIT: `Visitech AS`,
  VIZ: `Vizio`,
  VLB: `ValleyBoard Ltda.`,
  VLC: `VersaLogic Corporation`,
  VLK: `Vislink International`,
  VLM: `Lenovo Beijing`,
  VLT: `VideoLan Technologies`,
  VLV: `Valve Corporation`,
  VMI: `Vermont Microsystems`,
  VML: `Vine Micros`,
  VMW: `VMware`,
  VNC: `Vinca Corporation`,
  VNX: `Venetex Corporation`,
  VOB: `MaxData Computer AG`,
  VPI: `Video Products`,
  VPR: `Best Buy`,
  VPX: `VPixx Technologies`,
  VRC: `Virtual Resources Corporation`,
  VRG: `VRgineers`,
  VRM: `VRmagic Holding AG`,
  VRS: `VRstudios`,
  VRT: `Varjo Technologies`,
  VSC: `ViewSonic Corporation`,
  VSD: `3M`,
  VSI: `VideoServer`,
  VSN: `Ingram Macrotron`,
  VSP: `Vision Systems GmbH`,
  VSR: `V-Star Electronics`,
  VTB: `Videotechnik Breithaupt`,
  VTC: `VTel Corporation`,
  VTG: `Voice Technologies Group`,
  VTI: `VLSI Tech`,
  VTK: `Viewteck`,
  VTL: `Vivid Technology Pte`,
  VTM: `Miltope Corporation`,
  VTN: `Videotron Corp.`,
  VTS: `VTech Computers`,
  VTV: `VATIV Technologies`,
  VTX: `Vestax Corporation`,
  VUT: `Vutrix (UK)`,
  VVI: `VITEC`,
  VWB: `Vweb Corp.`,
  WAC: `Wacom Tech`,
  WAL: `Wave Access`,
  WAN: `DO NOT USE - WAN`,
  WAV: `Wavephore`,
  WBN: `MicroSoftWare`,
  WBS: `WB Systemtechnik GmbH`,
  WCI: `Wisecom`,
  WCS: `Woodwind Communications Systems`,
  WDC: `Western Digital`,
  WDE: `Westinghouse Digital Electronics`,
  WEB: `WebGear`,
  WEC: `Winbond Electronics Corporation`,
  WEL: `W-DEV`,
  WEY: `WEY Design AG`,
  WHI: `Whistle Communications`,
  WII: `Innoware`,
  WIL: `Wipro Information Technology`,
  WIN: `Wintop Technology`,
  WIP: `Wipro Infotech`,
  WKH: `Uni-Take Int'l`,
  WLD: `Wildfire Communications`,
  WLF: `WOLF Advanced Technology`,
  WMI: `Weidmuller Interface GmbH & Co. KG`,
  WML: `Wolfson Microelectronics`,
  WMO: `Westermo Teleindustri AB`,
  WMT: `Winmate Communication`,
  WNI: `WillNet`,
  WNV: `Winnov L.P.`,
  WNX: `Diebold Nixdorf Systems GmbH`,
  WPA: `Matsushita Communication Industrial`,
  WPI: `Wearnes Peripherals International (Pte)`,
  WRC: `WiNRADiO Communications`,
  WSC: `CIS Technology`,
  WSP: `Wireless And Smart Products`,
  WST: `Wistron Corporation`,
  WTC: `ACC Microelectronics`,
  WTI: `WorkStation Tech`,
  WTK: `Wearnes Thakral Pte`,
  WTS: `Restek Electric Company`,
  WVM: `Wave Systems Corporation`,
  WVV: `WolfVision GmbH`,
  WWP: `Wipotec Wiege- und Positioniersysteme GmbH`,
  WWV: `World Wide Video`,
  WXT: `Woxter Technology`,
  WYR: `WyreStorm Technologies`,
  WYS: `Myse Technology`,
  WYT: `Wooyoung Image & Information`,
  XAC: `XAC Automation Corp`,
  XAD: `Alpha Data`,
  XDM: `XDM`,
  XER: `DO NOT USE - XER`,
  XES: `Extreme Engineering Solutions`,
  XFG: `Jan Strapko - FOTO`,
  XFO: `EXFO Electro Optical Engineering`,
  XIN: `Xinex Networks`,
  XIO: `Xiotech Corporation`,
  XIR: `Xirocm`,
  XIT: `Xitel`,
  XLX: `Xilinx`,
  XMI: `Xiaomi Corporation`,
  XMM: `C3PO S.L.`,
  XNT: `XN Technologies`,
  XOC: `DO NOT USE - XOC`,
  XQU: `Shanghai SVA-DAV Electronics`,
  XRC: `Xircom`,
  XRO: `Xoro Electronics (Chengdu)`,
  XSN: `Xscreen AS`,
  XST: `XS Technologies`,
  XSY: `XSYS`,
  XTD: `Icuiti Corporation`,
  XTE: `X2E GmbH`,
  XTL: `Crystal Computer`,
  XTN: `X-10 (USA)`,
  XYC: `Xycotec Computer GmbH`,
  XYE: `Shenzhen Zhuona Technology`,
  YED: `Y-E Data`,
  YHQ: `Yokogawa Electric Corporation`,
  YHW: `Exacom SA`,
  YMH: `Yamaha Corporation`,
  YOW: `American Biometric Company`,
  ZAN: `Zandar Technologies plc`,
  ZAX: `Zefiro Acoustics`,
  ZAZ: `ZeeVee`,
  ZBR: `Zebra Technologies International`,
  ZBX: `Zebax Technologies`,
  ZCT: `ZeitControl cardsystems GmbH`,
  ZCM: `Zenith Data Systems`,
  ZDS: `Zenith Data Systems`,
  ZEN: `ZENIC`,
  ZGT: `Zenith Data Systems`,
  ZIC: `Nationz Technologies`,
  ZMC: `HangZhou ZMCHIVIN`,
  ZMT: `Zalman Tech`,
  ZMZ: `Z Microsystems`,
  ZNI: `Zetinet`,
  ZNX: `Znyx Adv. Systems`,
  ZOW: `Zowie Intertainment`,
  ZRN: `Zoran Corporation`,
  ZSE: `Zenith Data Systems`,
  ZTC: `ZyDAS Technology Corporation`,
  ZTE: `ZTE Corporation`,
  ZTI: `Zoom Telephonics`,
  ZTM: `ZT Group Int'l`,
  ZTT: `Z3 Technology`,
  ZWE: `Shenzhen Zowee Technology`,
  ZYD: `Zydacron`,
  ZYP: `Zypcom`,
  ZYT: `Zytex Computers`,
  ZYX: `Zyxel`,
  ZZZ: `Boca Research`,
};
